# Appendix {-}

Here are miscellaneous skills, knowledge, and technologies I should know.

## Publishing to BookDown {-}

The **bookdown** package, written by Yihui Xie, is built on top of R Markdown and the **knitr** package.  Use it to publish a book or long manuscript where each chapter is a separate file.  There are instructions for how to author a book in his [bookdown book](https://bookdown.org/yihui/bookdown/) [@xie2019].  The main advantage of **bookdown** over R Markdown is that you can produce multi-page HTML output with numbered headers, equations, figures, etc., just like in a book.  I'm using **bookdown** to create a compendium of all my data science notes.  

The first step to using **bookdown** is installing the **bookdown* package with `install.packages("bookdown")`.

Next, create an account at [bookdown.org](http://bookdown.org), and connect the account to RStudio.  Follow the instructions at [https://bookdown.org/home/about/](https://bookdown.org/home/about/).

Finally, create a project in R Studio by creating a new project of type *Book Project using Bookdown*.

After creating all of your Markdown pages, knit the book or click the **Build Book** button in the Build panel.


## Shiny Apps {-}

## Create Package {-}

Consult the book **R Packages** [@Wickham2015] by Hadley Wickham.  Basic instructions:

1. In RStudio, File > New Project.  Select "New Directory".  Select "R Package".
2. Write functions in R scripts in R directory.  Document with tags readable by *roxygen2* package.
3. Select XYZ > Install and Restart.

If creating an Rmd template, use `use_this::use_rmarkdown_template()`.  Here is how I created the "Kaggle Report" template.

```{r eval=FALSE}
use_rmarkdown_template(
  template_name = "Kaggle Report",
  template_dir = "kaggle_report",
  template_description = "Template for creating Kaggle reports in RMarkdown.",
  template_create_dir = FALSE
)
```

Learn more about R Markdown and templates in Yihui Xie's **R Markdown: The Definitive Guide** [@Xie2019b].

 Open Source Software for Data Science
 Data, visualization, and designing with AI
 Deploying End-to-End Data Science with Shiny, Plumber, and Pins
 Health Connected Siloed Data Sources and Streamlined Reporting Using R
 Builiding a new data science pipeline for teh FT with RStudio Connect
 How to win an AI Hackathon without using AI
 Production-grade Shiny Apps with golem
 Making the Shiny Contest
 Styling Shiny apps with Sass and Bootstrap 4
 R: Then and Now
 Journalism with RStudio, R, and teh Tidyverse
 Learning R with humorous side projects - or - Technical debt is a social problem
 FlatironKitchen: How we overhauled a Frankensteinian SQL workflow with the tidyverse
 Making better spaghetti (plots): Exploring longitudinal data with brolgar package

 Object of type 'closure' is not subsettable
 Branding and Packaging Reports with R Markdown
 The Glamour of Graphics
 Don't repeat yourself, talk to yourself! Repeated reporting in the R universe
 RStudio 1.3 Sneak Preview
 One R Markdown Document, Fourteen Demos - or - Tidyverse 2019-20
 Best Practices for programing with ggplot2
 Spruce up your ggplot2 visualization with formatted text
 The little package that could: taking visualization to the next level with the scales package
 Advances in tidyeval
 