<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5.3 Model Assumptions | My Data Science Notes</title>
  <meta name="description" content="This is a compendium of notes from classes, tutorials, etc. that I reference from time to time." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="5.3 Model Assumptions | My Data Science Notes" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a compendium of notes from classes, tutorials, etc. that I reference from time to time." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5.3 Model Assumptions | My Data Science Notes" />
  
  <meta name="twitter:description" content="This is a compendium of notes from classes, tutorials, etc. that I reference from time to time." />
  

<meta name="author" content="Michael Foley" />


<meta name="date" content="2020-07-07" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="parameter-estimation.html"/>
<link rel="next" href="prediction.html"/>
<script src="assets/jquery-2.2.3/jquery.min.js"></script>
<link href="assets/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="assets/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">My Data Science Notes</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Intro</a></li>
<li class="chapter" data-level="1" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i><b>1</b> Probability</a><ul>
<li class="chapter" data-level="1.1" data-path="principles.html"><a href="principles.html"><i class="fa fa-check"></i><b>1.1</b> Principles</a></li>
<li class="chapter" data-level="1.2" data-path="disc-dist.html"><a href="disc-dist.html"><i class="fa fa-check"></i><b>1.2</b> Discrete Distributions</a><ul>
<li class="chapter" data-level="1.2.1" data-path="disc-dist.html"><a href="disc-dist.html#bernoulli"><i class="fa fa-check"></i><b>1.2.1</b> Bernoulli</a></li>
<li class="chapter" data-level="1.2.2" data-path="disc-dist.html"><a href="disc-dist.html#binomial"><i class="fa fa-check"></i><b>1.2.2</b> Binomial</a></li>
<li class="chapter" data-level="1.2.3" data-path="disc-dist.html"><a href="disc-dist.html#poission"><i class="fa fa-check"></i><b>1.2.3</b> Poission</a></li>
<li class="chapter" data-level="1.2.4" data-path="disc-dist.html"><a href="disc-dist.html#multinomial"><i class="fa fa-check"></i><b>1.2.4</b> Multinomial</a></li>
<li class="chapter" data-level="1.2.5" data-path="disc-dist.html"><a href="disc-dist.html#negative-binomial"><i class="fa fa-check"></i><b>1.2.5</b> Negative-Binomial</a></li>
<li class="chapter" data-level="1.2.6" data-path="disc-dist.html"><a href="disc-dist.html#geometric"><i class="fa fa-check"></i><b>1.2.6</b> Geometric</a></li>
<li class="chapter" data-level="1.2.7" data-path="disc-dist.html"><a href="disc-dist.html#hypergeometric"><i class="fa fa-check"></i><b>1.2.7</b> Hypergeometric</a></li>
<li class="chapter" data-level="1.2.8" data-path="disc-dist.html"><a href="disc-dist.html#gamma"><i class="fa fa-check"></i><b>1.2.8</b> Gamma</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="cont-dist.html"><a href="cont-dist.html"><i class="fa fa-check"></i><b>1.3</b> Continuous Distributions</a><ul>
<li class="chapter" data-level="1.3.1" data-path="cont-dist.html"><a href="cont-dist.html#normal"><i class="fa fa-check"></i><b>1.3.1</b> Normal</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="join-distributions.html"><a href="join-distributions.html"><i class="fa fa-check"></i><b>1.4</b> Join Distributions</a></li>
<li class="chapter" data-level="1.5" data-path="likelihood.html"><a href="likelihood.html"><i class="fa fa-check"></i><b>1.5</b> Likelihood</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="discrete-analysis.html"><a href="discrete-analysis.html"><i class="fa fa-check"></i><b>2</b> Categorical Analysis - Nonmodel</a><ul>
<li class="chapter" data-level="2.1" data-path="chi-square-test.html"><a href="chi-square-test.html"><i class="fa fa-check"></i><b>2.1</b> Chi-Square Test</a></li>
<li class="chapter" data-level="2.2" data-path="one-way-tables.html"><a href="one-way-tables.html"><i class="fa fa-check"></i><b>2.2</b> One-Way Tables</a><ul>
<li class="chapter" data-level="2.2.1" data-path="one-way-tables.html"><a href="one-way-tables.html#chi-square-goodness-of-fit-test"><i class="fa fa-check"></i><b>2.2.1</b> Chi-Square Goodness-of-Fit Test</a></li>
<li class="chapter" data-level="2.2.2" data-path="one-way-tables.html"><a href="one-way-tables.html#proportion-test"><i class="fa fa-check"></i><b>2.2.2</b> Proportion Test</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="two-way-tables.html"><a href="two-way-tables.html"><i class="fa fa-check"></i><b>2.3</b> Two-Way Tables</a><ul>
<li class="chapter" data-level="2.3.1" data-path="two-way-tables.html"><a href="two-way-tables.html#chi-square-independence-test"><i class="fa fa-check"></i><b>2.3.1</b> Chi-Square Independence Test</a></li>
<li class="chapter" data-level="2.3.2" data-path="two-way-tables.html"><a href="two-way-tables.html#residuals-analysis"><i class="fa fa-check"></i><b>2.3.2</b> Residuals Analysis</a></li>
<li class="chapter" data-level="2.3.3" data-path="two-way-tables.html"><a href="two-way-tables.html#difference-in-proportions"><i class="fa fa-check"></i><b>2.3.3</b> Difference in Proportions</a></li>
<li class="chapter" data-level="2.3.4" data-path="two-way-tables.html"><a href="two-way-tables.html#relative-risk"><i class="fa fa-check"></i><b>2.3.4</b> Relative Risk</a></li>
<li class="chapter" data-level="2.3.5" data-path="two-way-tables.html"><a href="two-way-tables.html#odds-ratio"><i class="fa fa-check"></i><b>2.3.5</b> Odds Ratio</a></li>
<li class="chapter" data-level="2.3.6" data-path="two-way-tables.html"><a href="two-way-tables.html#partitioning-chi-square"><i class="fa fa-check"></i><b>2.3.6</b> Partitioning Chi-Square</a></li>
<li class="chapter" data-level="2.3.7" data-path="two-way-tables.html"><a href="two-way-tables.html#correlation"><i class="fa fa-check"></i><b>2.3.7</b> Correlation</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="k-way-tables.html"><a href="k-way-tables.html"><i class="fa fa-check"></i><b>2.4</b> K-Way Tables</a><ul>
<li class="chapter" data-level="2.4.1" data-path="k-way-tables.html"><a href="k-way-tables.html#odds-ratio-1"><i class="fa fa-check"></i><b>2.4.1</b> Odds Ratio</a></li>
<li class="chapter" data-level="2.4.2" data-path="k-way-tables.html"><a href="k-way-tables.html#chi-square-independence-test-1"><i class="fa fa-check"></i><b>2.4.2</b> Chi-Square Independence Test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="continuous-analysis.html"><a href="continuous-analysis.html"><i class="fa fa-check"></i><b>3</b> Continuous Variable Analysis</a><ul>
<li class="chapter" data-level="3.0.1" data-path="two-way-tables.html"><a href="two-way-tables.html#correlation"><i class="fa fa-check"></i><b>3.0.1</b> Correlation</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="experiment-design.html"><a href="experiment-design.html"><i class="fa fa-check"></i><b>4</b> Experiment Design</a><ul>
<li class="chapter" data-level="4.1" data-path="single-factor.html"><a href="single-factor.html"><i class="fa fa-check"></i><b>4.1</b> Single Factor</a></li>
<li class="chapter" data-level="4.2" data-path="blocking.html"><a href="blocking.html"><i class="fa fa-check"></i><b>4.2</b> Blocking</a></li>
<li class="chapter" data-level="4.3" data-path="nested.html"><a href="nested.html"><i class="fa fa-check"></i><b>4.3</b> Nested</a></li>
<li class="chapter" data-level="4.4" data-path="split-plot.html"><a href="split-plot.html"><i class="fa fa-check"></i><b>4.4</b> Split Plot</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-2-supervised-machine-learning.html"><a href="part-2-supervised-machine-learning.html"><i class="fa fa-check"></i>PART 2: Supervised Machine Learning</a></li>
<li class="chapter" data-level="5" data-path="ordinary-least-squares.html"><a href="ordinary-least-squares.html"><i class="fa fa-check"></i><b>5</b> Ordinary Least Squares</a><ul>
<li class="chapter" data-level="5.1" data-path="linear-regression-model.html"><a href="linear-regression-model.html"><i class="fa fa-check"></i><b>5.1</b> Linear Regression Model</a></li>
<li class="chapter" data-level="5.2" data-path="parameter-estimation.html"><a href="parameter-estimation.html"><i class="fa fa-check"></i><b>5.2</b> Parameter Estimation</a></li>
<li class="chapter" data-level="5.3" data-path="model-assumptions.html"><a href="model-assumptions.html"><i class="fa fa-check"></i><b>5.3</b> Model Assumptions</a><ul>
<li class="chapter" data-level="5.3.1" data-path="model-assumptions.html"><a href="model-assumptions.html#linearity"><i class="fa fa-check"></i><b>5.3.1</b> Linearity</a></li>
<li class="chapter" data-level="5.3.2" data-path="model-assumptions.html"><a href="model-assumptions.html#multicollinearity"><i class="fa fa-check"></i><b>5.3.2</b> Multicollinearity</a></li>
<li class="chapter" data-level="5.3.3" data-path="model-assumptions.html"><a href="model-assumptions.html#normality"><i class="fa fa-check"></i><b>5.3.3</b> Normality</a></li>
<li class="chapter" data-level="5.3.4" data-path="model-assumptions.html"><a href="model-assumptions.html#equal-variances"><i class="fa fa-check"></i><b>5.3.4</b> Equal Variances</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="prediction.html"><a href="prediction.html"><i class="fa fa-check"></i><b>5.4</b> Prediction</a></li>
<li class="chapter" data-level="5.5" data-path="inference.html"><a href="inference.html"><i class="fa fa-check"></i><b>5.5</b> Inference</a><ul>
<li class="chapter" data-level="5.5.1" data-path="inference.html"><a href="inference.html#t-test"><i class="fa fa-check"></i><b>5.5.1</b> <em>t</em>-Test</a></li>
<li class="chapter" data-level="5.5.2" data-path="inference.html"><a href="inference.html#f-test"><i class="fa fa-check"></i><b>5.5.2</b> <em>F</em>-Test</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="interpretation.html"><a href="interpretation.html"><i class="fa fa-check"></i><b>5.6</b> Interpretation</a></li>
<li class="chapter" data-level="5.7" data-path="model-validation.html"><a href="model-validation.html"><i class="fa fa-check"></i><b>5.7</b> Model Validation</a><ul>
<li class="chapter" data-level="5.7.1" data-path="model-validation.html"><a href="model-validation.html#accuracy-metrics"><i class="fa fa-check"></i><b>5.7.1</b> Accuracy Metrics</a></li>
<li class="chapter" data-level="5.7.2" data-path="model-validation.html"><a href="model-validation.html#cross-validation"><i class="fa fa-check"></i><b>5.7.2</b> Cross-Validation</a></li>
<li class="chapter" data-level="5.7.3" data-path="model-validation.html"><a href="model-validation.html#gain-curve"><i class="fa fa-check"></i><b>5.7.3</b> Gain Curve</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="reference.html"><a href="reference.html"><i class="fa fa-check"></i><b>5.8</b> Reference</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html"><i class="fa fa-check"></i><b>6</b> Generalized Linear Models</a><ul>
<li class="chapter" data-level="6.1" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>6.1</b> Logistic Regression</a></li>
<li class="chapter" data-level="6.2" data-path="multinomial-logistic-regression.html"><a href="multinomial-logistic-regression.html"><i class="fa fa-check"></i><b>6.2</b> Multinomial Logistic Regression</a></li>
<li class="chapter" data-level="6.3" data-path="ordinal-logistic-regression.html"><a href="ordinal-logistic-regression.html"><i class="fa fa-check"></i><b>6.3</b> Ordinal Logistic Regression</a><ul>
<li class="chapter" data-level="6.3.1" data-path="ordinal-logistic-regression.html"><a href="ordinal-logistic-regression.html#assumptions"><i class="fa fa-check"></i><b>6.3.1</b> Assumptions</a></li>
<li class="chapter" data-level="6.3.2" data-path="ordinal-logistic-regression.html"><a href="ordinal-logistic-regression.html#modeling"><i class="fa fa-check"></i><b>6.3.2</b> Modeling</a></li>
<li class="chapter" data-level="6.3.3" data-path="ordinal-logistic-regression.html"><a href="ordinal-logistic-regression.html#case-study"><i class="fa fa-check"></i><b>6.3.3</b> Case Study</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="poisson-regression.html"><a href="poisson-regression.html"><i class="fa fa-check"></i><b>6.4</b> Poisson Regression</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="multivariate-statistical-analysis.html"><a href="multivariate-statistical-analysis.html"><i class="fa fa-check"></i><b>7</b> Multivariate Statistical Analysis</a><ul>
<li class="chapter" data-level="7.1" data-path="background.html"><a href="background.html"><i class="fa fa-check"></i><b>7.1</b> Background</a></li>
<li class="chapter" data-level="7.2" data-path="manova.html"><a href="manova.html"><i class="fa fa-check"></i><b>7.2</b> MANOVA</a></li>
<li class="chapter" data-level="7.3" data-path="repeated-measures.html"><a href="repeated-measures.html"><i class="fa fa-check"></i><b>7.3</b> Repeated Measures</a></li>
<li class="chapter" data-level="7.4" data-path="lda.html"><a href="lda.html"><i class="fa fa-check"></i><b>7.4</b> LDA</a></li>
<li class="chapter" data-level="7.5" data-path="pca.html"><a href="pca.html"><i class="fa fa-check"></i><b>7.5</b> PCA</a></li>
<li class="chapter" data-level="7.6" data-path="factor-analysis.html"><a href="factor-analysis.html"><i class="fa fa-check"></i><b>7.6</b> Factor Analysis</a></li>
<li class="chapter" data-level="7.7" data-path="canonical-correlation.html"><a href="canonical-correlation.html"><i class="fa fa-check"></i><b>7.7</b> Canonical Correlation</a></li>
<li class="chapter" data-level="7.8" data-path="cluster-analysis.html"><a href="cluster-analysis.html"><i class="fa fa-check"></i><b>7.8</b> Cluster Analysis</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="classification.html"><a href="classification.html"><i class="fa fa-check"></i><b>8</b> Classification</a></li>
<li class="chapter" data-level="9" data-path="regularization.html"><a href="regularization.html"><i class="fa fa-check"></i><b>9</b> Regularization</a><ul>
<li class="chapter" data-level="9.1" data-path="ridge.html"><a href="ridge.html"><i class="fa fa-check"></i><b>9.1</b> Ridge</a></li>
<li class="chapter" data-level="9.2" data-path="lasso.html"><a href="lasso.html"><i class="fa fa-check"></i><b>9.2</b> Lasso</a></li>
<li class="chapter" data-level="9.3" data-path="elastic-net.html"><a href="elastic-net.html"><i class="fa fa-check"></i><b>9.3</b> Elastic Net</a></li>
<li class="chapter" data-level="" data-path="model-summary.html"><a href="model-summary.html"><i class="fa fa-check"></i>Model Summary</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="decision-trees.html"><a href="decision-trees.html"><i class="fa fa-check"></i><b>10</b> Decision Trees</a><ul>
<li class="chapter" data-level="10.1" data-path="classification-tree.html"><a href="classification-tree.html"><i class="fa fa-check"></i><b>10.1</b> Classification Tree</a><ul>
<li class="chapter" data-level="10.1.1" data-path="classification-tree.html"><a href="classification-tree.html#measuring-performance"><i class="fa fa-check"></i><b>10.1.1</b> Measuring Performance</a></li>
<li class="chapter" data-level="10.1.2" data-path="classification-tree.html"><a href="classification-tree.html#training-with-caret"><i class="fa fa-check"></i><b>10.1.2</b> Training with Caret</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="regression-tree.html"><a href="regression-tree.html"><i class="fa fa-check"></i><b>10.2</b> Regression Tree</a><ul>
<li class="chapter" data-level="10.2.1" data-path="regression-tree.html"><a href="regression-tree.html#training-with-caret-1"><i class="fa fa-check"></i><b>10.2.1</b> Training with Caret</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="bagged-trees.html"><a href="bagged-trees.html"><i class="fa fa-check"></i><b>10.3</b> Bagged Trees</a><ul>
<li class="chapter" data-level="10.3.1" data-path="bagged-trees.html"><a href="bagged-trees.html#bagged-classification-tree"><i class="fa fa-check"></i><b>10.3.1</b> Bagged Classification Tree</a></li>
<li class="chapter" data-level="10.3.2" data-path="bagged-trees.html"><a href="bagged-trees.html#bagging-regression-tree"><i class="fa fa-check"></i><b>10.3.2</b> Bagging Regression Tree</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="random-forests.html"><a href="random-forests.html"><i class="fa fa-check"></i><b>10.4</b> Random Forests</a></li>
<li class="chapter" data-level="10.5" data-path="gradient-boosting.html"><a href="gradient-boosting.html"><i class="fa fa-check"></i><b>10.5</b> Gradient Boosting</a></li>
<li class="chapter" data-level="10.6" data-path="summary.html"><a href="summary.html"><i class="fa fa-check"></i><b>10.6</b> Summary</a><ul>
<li class="chapter" data-level="10.6.1" data-path="summary.html"><a href="summary.html#classification-trees"><i class="fa fa-check"></i><b>10.6.1</b> Classification Trees</a></li>
<li class="chapter" data-level="10.6.2" data-path="summary.html"><a href="summary.html#regression-trees"><i class="fa fa-check"></i><b>10.6.2</b> Regression Trees</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="reference.html"><a href="reference.html#reference"><i class="fa fa-check"></i><b>10.7</b> Reference</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="non-linear-models.html"><a href="non-linear-models.html"><i class="fa fa-check"></i><b>11</b> Non-linear Models</a><ul>
<li class="chapter" data-level="11.1" data-path="splines.html"><a href="splines.html"><i class="fa fa-check"></i><b>11.1</b> Splines</a></li>
<li class="chapter" data-level="11.2" data-path="mars.html"><a href="mars.html"><i class="fa fa-check"></i><b>11.2</b> MARS</a></li>
<li class="chapter" data-level="11.3" data-path="gam.html"><a href="gam.html"><i class="fa fa-check"></i><b>11.3</b> GAM</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="support-vector-machines.html"><a href="support-vector-machines.html"><i class="fa fa-check"></i><b>12</b> Support Vector Machines</a><ul>
<li class="chapter" data-level="12.1" data-path="maximal-margin-classifier.html"><a href="maximal-margin-classifier.html"><i class="fa fa-check"></i><b>12.1</b> Maximal Margin Classifier</a></li>
<li class="chapter" data-level="12.2" data-path="support-vector-classifier.html"><a href="support-vector-classifier.html"><i class="fa fa-check"></i><b>12.2</b> Support Vector Classifier</a></li>
<li class="chapter" data-level="12.3" data-path="support-vector-machines-1.html"><a href="support-vector-machines-1.html"><i class="fa fa-check"></i><b>12.3</b> Support Vector Machines</a></li>
<li class="chapter" data-level="12.4" data-path="disc-dist.html"><a href="disc-dist.html#example"><i class="fa fa-check"></i><b>12.4</b> Example</a></li>
<li class="chapter" data-level="12.5" data-path="using-caret.html"><a href="using-caret.html"><i class="fa fa-check"></i><b>12.5</b> Using Caret</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="principal-components-analysis.html"><a href="principal-components-analysis.html"><i class="fa fa-check"></i><b>13</b> Principal Components Analysis</a></li>
<li class="chapter" data-level="14" data-path="text-mining.html"><a href="text-mining.html"><i class="fa fa-check"></i><b>14</b> Text Mining</a><ul>
<li class="chapter" data-level="14.1" data-path="n-grams.html"><a href="n-grams.html"><i class="fa fa-check"></i><b>14.1</b> N-Grams</a></li>
<li class="chapter" data-level="14.2" data-path="converting-to-and-from-non-tidy-formats.html"><a href="converting-to-and-from-non-tidy-formats.html"><i class="fa fa-check"></i><b>14.2</b> Converting to and from non-tidy formats</a></li>
<li class="chapter" data-level="14.3" data-path="disc-dist.html"><a href="disc-dist.html#example"><i class="fa fa-check"></i><b>14.3</b> Example</a></li>
<li class="chapter" data-level="14.4" data-path="stringr-package.html"><a href="stringr-package.html"><i class="fa fa-check"></i><b>14.4</b> stringr package</a></li>
<li class="chapter" data-level="14.5" data-path="regular-expressions.html"><a href="regular-expressions.html"><i class="fa fa-check"></i><b>14.5</b> Regular Expressions</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="survival-analysis.html"><a href="survival-analysis.html"><i class="fa fa-check"></i><b>15</b> Survival Analysis</a><ul>
<li class="chapter" data-level="15.1" data-path="basic-concepts.html"><a href="basic-concepts.html"><i class="fa fa-check"></i><b>15.1</b> Basic Concepts</a></li>
<li class="chapter" data-level="15.2" data-path="survival-curve-estimation.html"><a href="survival-curve-estimation.html"><i class="fa fa-check"></i><b>15.2</b> Survival Curve Estimation</a><ul>
<li class="chapter" data-level="15.2.1" data-path="survival-curve-estimation.html"><a href="survival-curve-estimation.html#kaplan-meier"><i class="fa fa-check"></i><b>15.2.1</b> Kaplan-Meier</a></li>
<li class="chapter" data-level="15.2.2" data-path="survival-curve-estimation.html"><a href="survival-curve-estimation.html#weibull"><i class="fa fa-check"></i><b>15.2.2</b> Weibull</a></li>
<li class="chapter" data-level="15.2.3" data-path="survival-curve-estimation.html"><a href="survival-curve-estimation.html#cox"><i class="fa fa-check"></i><b>15.2.3</b> Cox</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html"><i class="fa fa-check"></i>Appendix</a><ul>
<li class="chapter" data-level="" data-path="publishing-to-bookdown.html"><a href="publishing-to-bookdown.html"><i class="fa fa-check"></i>Publishing to BookDown</a></li>
<li class="chapter" data-level="" data-path="shiny-apps.html"><a href="shiny-apps.html"><i class="fa fa-check"></i>Shiny Apps</a></li>
<li class="chapter" data-level="" data-path="packages.html"><a href="packages.html"><i class="fa fa-check"></i>Packages</a><ul>
<li class="chapter" data-level="" data-path="packages.html"><a href="packages.html#create-a-package"><i class="fa fa-check"></i>Create a package</a></li>
<li class="chapter" data-level="15.2.4" data-path="packages.html"><a href="packages.html#document-functions-with-roxygen"><i class="fa fa-check"></i><b>15.2.4</b> Document Functions with roxygen</a></li>
<li class="chapter" data-level="" data-path="packages.html"><a href="packages.html#create-data"><i class="fa fa-check"></i>Create Data</a></li>
<li class="chapter" data-level="" data-path="packages.html"><a href="packages.html#create-vignette"><i class="fa fa-check"></i>Create Vignette</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">My Data Science Notes</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="model-assumptions" class="section level2">
<h2><span class="header-section-number">5.3</span> Model Assumptions</h2>
<p>The linear regression model assumes the relationship between the predictors and the response is linear with the residuals that are independent random variables normally distributed with mean zero and constant variance.</p>
<p>Additionally, you will want to check for multicollinearity in the predictors because it can produce unreliable coefficient estimates and predicted values.</p>
<p>Use a residuals vs fits plot <span class="math inline">\(\left( e \sim \hat{Y} \right)\)</span> to detect non-linearity and unequal error variances, including outliers. The polynomial trend line should show that the residuals vary around <span class="math inline">\(e = 0\)</span> in a straight line (linearity). The variance should be of constant width (especially no fan shape at the low or high ends).</p>
<p>Use a residuals normal probability plot to compares the theoretical percentiles of the normal distribution versus the observed sample percentiles. It should be approximately linear.</p>
<p>A scale-location plot <span class="math inline">\(\sqrt{e / sd(e)} \sim \hat{y}\)</span> checks the homogeneity of variance of the residuals (homoscedasticity). The square root of the absolute value of the residuals should be spread equally along a horizontal line.</p>
<p>A residuals vs leverage plot identifies influential observations. A plot of the standardized residuals vs the leverage should fall within the 95% probability band.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="model-assumptions.html#cb20-1"></a><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb20-2"><a href="model-assumptions.html#cb20-2"></a><span class="kw">plot</span>(m, <span class="dt">labels.id =</span> <span class="ot">NULL</span>)</span></code></pre></div>
<p><img src="data-sci_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<div id="linearity" class="section level3">
<h3><span class="header-section-number">5.3.1</span> Linearity</h3>
<p>The explanatory variables should each be linearly related to the response variable: <span class="math inline">\(E(\epsilon | X_j) = 0\)</span>. A good way to test this condition is with a residuals vs fitted values plot. A curved pattern in the residuals indicates a curvature in the relationship between the response and the predictor that is not explained by our model. A linear model does not adequately describe the relationship between the predictor and the response.</p>
<p>Test for linearity four ways:</p>
<ul>
<li>Residuals vs fits plot <span class="math inline">\((e \sim \hat{Y})\)</span> should bounce randomly around 0.</li>
<li>Observed vs fits plot <span class="math inline">\((Y \sim \hat{Y})\)</span> should be symmetric along the 45-degree line.<br />
</li>
<li>Each <span class="math inline">\((Y \sim X_j )\)</span> plot should have correlation <span class="math inline">\(\rho \sim 1\)</span>.<br />
</li>
<li>Each <span class="math inline">\((e \sim X_j)\)</span> plot should exhibit no pattern.</li>
</ul>
<p>If the linearity condition fails, change the functional form of the model with non-linear transformations of the explanatory variables. A common way to do this is with Box-Cox transformations.</p>
<p><span class="math display">\[w_t = \begin{cases} \begin{array}{l} log(y_t) \quad \quad \lambda = 0 \\
(y_t^\lambda - 1) / \lambda \quad \text{otherwise} \end{array} \end{cases}\]</span></p>
<p><span class="math inline">\(\lambda\)</span> can take any value, but values near the following yield familiar transformations.</p>
<ul>
<li><span class="math inline">\(\lambda = 1\)</span> yields no substantive transformation.<br />
</li>
<li><span class="math inline">\(\lambda = 0.5\)</span> is a square root plus linear transformation.</li>
<li><span class="math inline">\(\lambda = 0.333\)</span> is a cube root plus linear transformation.</li>
<li><span class="math inline">\(\lambda = 0\)</span> is a natural log transformation.</li>
<li><span class="math inline">\(\lambda = -1\)</span> is an inverse transformation.</li>
</ul>
<p>A common source of non-linearity in a model is skewed response or independent variables (see discussion <a href="https://blog.minitab.com/blog/applying-statistics-in-quality-projects/how-could-you-benefit-from-a-box-cox-transformation">here</a>). <code>mtcars</code> has some skewed variables.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="model-assumptions.html#cb21-1"></a>tmp &lt;-<span class="st"> </span><span class="kw">map</span>(mtcars, skewness) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb21-2"><a href="model-assumptions.html#cb21-2"></a><span class="st">  </span><span class="kw">unlist</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb21-3"><a href="model-assumptions.html#cb21-3"></a><span class="st">  </span><span class="kw">as.data.frame</span>() <span class="op">%&gt;%</span></span>
<span id="cb21-4"><a href="model-assumptions.html#cb21-4"></a><span class="st">  </span><span class="kw">rownames_to_column</span>() </span>
<span id="cb21-5"><a href="model-assumptions.html#cb21-5"></a><span class="kw">colnames</span>(tmp) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;IV&quot;</span>, <span class="st">&quot;skew&quot;</span>)</span>
<span id="cb21-6"><a href="model-assumptions.html#cb21-6"></a><span class="kw">ggplot</span>(tmp, <span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">order</span>(IV, skew), <span class="dt">y =</span> skew)) <span class="op">+</span></span>
<span id="cb21-7"><a href="model-assumptions.html#cb21-7"></a><span class="st">  </span><span class="kw">geom_col</span>()</span></code></pre></div>
<p><img src="data-sci_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="model-assumptions.html#cb22-1"></a>df &lt;-<span class="st"> </span>mtcars</span>
<span id="cb22-2"><a href="model-assumptions.html#cb22-2"></a>m &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>hp, <span class="dt">data =</span> df)</span>
<span id="cb22-3"><a href="model-assumptions.html#cb22-3"></a><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb22-4"><a href="model-assumptions.html#cb22-4"></a><span class="kw">plot</span>(m)</span></code></pre></div>
<p><img src="data-sci_files/figure-html/unnamed-chunk-12-2.png" width="672" /></p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="model-assumptions.html#cb23-1"></a><span class="kw">plot</span>(m<span class="op">$</span>model<span class="op">$</span>mpg, m<span class="op">$</span>fitted.values)</span>
<span id="cb23-2"><a href="model-assumptions.html#cb23-2"></a><span class="kw">abline</span>(<span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb23-3"><a href="model-assumptions.html#cb23-3"></a><span class="kw">cor</span>(df<span class="op">$</span>mpg, df<span class="op">$</span>hp)</span></code></pre></div>
<pre><code>## [1] -0.7761684</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="model-assumptions.html#cb25-1"></a><span class="kw">postResample</span>(<span class="dt">pred =</span> m<span class="op">$</span>fitted.values, <span class="dt">obs =</span> m<span class="op">$</span>model<span class="op">$</span>mpg)</span></code></pre></div>
<pre><code>##      RMSE  Rsquared       MAE 
## 3.7402971 0.6024373 2.9074525</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="model-assumptions.html#cb27-1"></a>bc &lt;-<span class="st"> </span><span class="kw">BoxCoxTrans</span>(mtcars<span class="op">$</span>hp)</span>
<span id="cb27-2"><a href="model-assumptions.html#cb27-2"></a>df<span class="op">$</span>hp_bc &lt;-<span class="st"> </span><span class="kw">predict</span>(bc, mtcars<span class="op">$</span>hp)</span>
<span id="cb27-3"><a href="model-assumptions.html#cb27-3"></a>m_bc &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>hp_bc, <span class="dt">data =</span> df)</span>
<span id="cb27-4"><a href="model-assumptions.html#cb27-4"></a><span class="kw">plot</span>(m_bc)</span></code></pre></div>
<p><img src="data-sci_files/figure-html/unnamed-chunk-12-3.png" width="672" /></p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="model-assumptions.html#cb28-1"></a><span class="kw">plot</span>(m_bc<span class="op">$</span>model<span class="op">$</span>mpg, m_bc<span class="op">$</span>fitted.values)</span>
<span id="cb28-2"><a href="model-assumptions.html#cb28-2"></a><span class="kw">abline</span>(<span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb28-3"><a href="model-assumptions.html#cb28-3"></a><span class="kw">cor</span>(df<span class="op">$</span>mpg, df<span class="op">$</span>hp_bc)</span></code></pre></div>
<pre><code>## [1] -0.8487707</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="model-assumptions.html#cb30-1"></a><span class="kw">postResample</span>(<span class="dt">pred =</span> m_bc<span class="op">$</span>fitted.values, <span class="dt">obs =</span> m_bc<span class="op">$</span>model<span class="op">$</span>mpg)</span></code></pre></div>
<pre><code>##      RMSE  Rsquared       MAE 
## 3.1366261 0.7204118 2.4074705</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="model-assumptions.html#cb32-1"></a><span class="co"># Which vars are skewed?</span></span>
<span id="cb32-2"><a href="model-assumptions.html#cb32-2"></a><span class="kw">map</span>(mtcars, skewness)</span></code></pre></div>
<pre><code>## $mpg
## [1] 0.610655
## 
## $cyl
## [1] -0.1746119
## 
## $disp
## [1] 0.381657
## 
## $hp
## [1] 0.7260237
## 
## $drat
## [1] 0.2659039
## 
## $wt
## [1] 0.4231465
## 
## $qsec
## [1] 0.3690453
## 
## $vs
## [1] 0.2402577
## 
## $am
## [1] 0.3640159
## 
## $gear
## [1] 0.5288545
## 
## $carb
## [1] 1.050874</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="model-assumptions.html#cb34-1"></a><span class="co"># Benchmark model: mpg ~ hp</span></span>
<span id="cb34-2"><a href="model-assumptions.html#cb34-2"></a>d0 &lt;-<span class="st"> </span>mtcars</span>
<span id="cb34-3"><a href="model-assumptions.html#cb34-3"></a>m0 &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>hp, <span class="dt">data =</span> d0)</span>
<span id="cb34-4"><a href="model-assumptions.html#cb34-4"></a>d0 &lt;-<span class="st"> </span><span class="kw">augment</span>(m0, d0)</span>
<span id="cb34-5"><a href="model-assumptions.html#cb34-5"></a>d0.cor &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">cor</span>(d0<span class="op">$</span>mpg, d0<span class="op">$</span>hp), <span class="dv">2</span>)</span>
<span id="cb34-6"><a href="model-assumptions.html#cb34-6"></a></span>
<span id="cb34-7"><a href="model-assumptions.html#cb34-7"></a><span class="co"># Benchmark diagnostics</span></span>
<span id="cb34-8"><a href="model-assumptions.html#cb34-8"></a>p0a &lt;-<span class="st"> </span><span class="kw">ggplot</span>(d0, <span class="kw">aes</span>(<span class="dt">x =</span> hp, <span class="dt">y =</span> mpg)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb34-9"><a href="model-assumptions.html#cb34-9"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Response vs IV&quot;</span>,</span>
<span id="cb34-10"><a href="model-assumptions.html#cb34-10"></a>       <span class="dt">subtitle =</span> <span class="kw">paste0</span>(<span class="st">&quot;Correlation ~ 1?  (rho = &quot;</span>, d0.cor, <span class="st">&quot;)&quot;</span>))</span>
<span id="cb34-11"><a href="model-assumptions.html#cb34-11"></a>p0b &lt;-<span class="st"> </span><span class="kw">ggplot</span>(d0, <span class="kw">aes</span>(<span class="dt">x =</span> .fitted, <span class="dt">y =</span> .resid)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_abline</span>(<span class="dt">intercept =</span> <span class="dv">0</span>, <span class="dt">slope =</span> <span class="dv">0</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb34-12"><a href="model-assumptions.html#cb34-12"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Residuals vs Fits&quot;</span>,</span>
<span id="cb34-13"><a href="model-assumptions.html#cb34-13"></a>       <span class="dt">subtitle =</span> <span class="st">&quot;Random scatter?&quot;</span>)</span>
<span id="cb34-14"><a href="model-assumptions.html#cb34-14"></a>p0c &lt;-<span class="st"> </span><span class="kw">ggplot</span>(d0, <span class="kw">aes</span>(<span class="dt">x =</span> .fitted, <span class="dt">y =</span> mpg)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_abline</span>(<span class="dt">intercept =</span> <span class="dv">0</span>, <span class="dt">slope =</span> <span class="dv">1</span>) <span class="op">+</span></span>
<span id="cb34-15"><a href="model-assumptions.html#cb34-15"></a><span class="st">  </span><span class="kw">expand_limits</span>(<span class="dt">x =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">35</span>), <span class="dt">y =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">35</span>)) <span class="op">+</span></span>
<span id="cb34-16"><a href="model-assumptions.html#cb34-16"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Observed vs Fits&quot;</span>,</span>
<span id="cb34-17"><a href="model-assumptions.html#cb34-17"></a>       <span class="dt">subtitle =</span> <span class="st">&quot;Symmetric along 45 degree line?&quot;</span>)</span>
<span id="cb34-18"><a href="model-assumptions.html#cb34-18"></a>p0d &lt;-<span class="st"> </span><span class="kw">ggplot</span>(d0, <span class="kw">aes</span>(<span class="dt">x =</span> hp, <span class="dt">y =</span> .resid)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_abline</span>(<span class="dt">intercept =</span> <span class="dv">0</span>, <span class="dt">slope =</span> <span class="dv">0</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb34-19"><a href="model-assumptions.html#cb34-19"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Residuals vs IV&quot;</span>,</span>
<span id="cb34-20"><a href="model-assumptions.html#cb34-20"></a>       <span class="dt">subtitle =</span> <span class="st">&quot;Random scatter?&quot;</span>)</span>
<span id="cb34-21"><a href="model-assumptions.html#cb34-21"></a><span class="kw">grid.arrange</span>(p0a, p0b, p0c, p0d, <span class="dt">nrow =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="model-assumptions.html#cb36-1"></a><span class="co"># Benchmark performance</span></span>
<span id="cb36-2"><a href="model-assumptions.html#cb36-2"></a><span class="kw">postResample</span>(<span class="dt">pred =</span> m0<span class="op">$</span>fitted.values, <span class="dt">obs =</span> m0<span class="op">$</span>model<span class="op">$</span>mpg)</span></code></pre></div>
<pre><code>##      RMSE  Rsquared       MAE 
## 3.7402971 0.6024373 2.9074525</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="model-assumptions.html#cb38-1"></a><span class="co"># Box-Cox transform hp</span></span>
<span id="cb38-2"><a href="model-assumptions.html#cb38-2"></a>d1 &lt;-<span class="st"> </span>mtcars</span>
<span id="cb38-3"><a href="model-assumptions.html#cb38-3"></a>bc &lt;-<span class="st"> </span><span class="kw">BoxCoxTrans</span>(d1<span class="op">$</span>hp)</span>
<span id="cb38-4"><a href="model-assumptions.html#cb38-4"></a>d1<span class="op">$</span>hp_bc &lt;-<span class="st"> </span><span class="kw">predict</span>(bc, d1<span class="op">$</span>hp)</span>
<span id="cb38-5"><a href="model-assumptions.html#cb38-5"></a>m1 &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>hp_bc, <span class="dt">data =</span> d1)</span>
<span id="cb38-6"><a href="model-assumptions.html#cb38-6"></a>d1 &lt;-<span class="st"> </span><span class="kw">augment</span>(m1, d1)</span>
<span id="cb38-7"><a href="model-assumptions.html#cb38-7"></a>d1.cor &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">cor</span>(d1<span class="op">$</span>mpg, d1<span class="op">$</span>hp_bc), <span class="dv">2</span>)</span>
<span id="cb38-8"><a href="model-assumptions.html#cb38-8"></a></span>
<span id="cb38-9"><a href="model-assumptions.html#cb38-9"></a>p1a &lt;-<span class="st"> </span><span class="kw">ggplot</span>(d1, <span class="kw">aes</span>(<span class="dt">x =</span> hp_bc, <span class="dt">y =</span> mpg)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb38-10"><a href="model-assumptions.html#cb38-10"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Response vs IV&quot;</span>,</span>
<span id="cb38-11"><a href="model-assumptions.html#cb38-11"></a>       <span class="dt">subtitle =</span> <span class="kw">paste0</span>(<span class="st">&quot;Correlation ~ 1?  (rho = &quot;</span>, d1.cor, <span class="st">&quot;)&quot;</span>))</span>
<span id="cb38-12"><a href="model-assumptions.html#cb38-12"></a>p1b &lt;-<span class="st"> </span><span class="kw">ggplot</span>(d1, <span class="kw">aes</span>(<span class="dt">x =</span> .fitted, <span class="dt">y =</span> .resid)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_abline</span>(<span class="dt">intercept =</span> <span class="dv">0</span>, <span class="dt">slope =</span> <span class="dv">0</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb38-13"><a href="model-assumptions.html#cb38-13"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Residuals vs Fits&quot;</span>,</span>
<span id="cb38-14"><a href="model-assumptions.html#cb38-14"></a>       <span class="dt">subtitle =</span> <span class="st">&quot;Random scatter?&quot;</span>)</span>
<span id="cb38-15"><a href="model-assumptions.html#cb38-15"></a>p1c &lt;-<span class="st"> </span><span class="kw">ggplot</span>(d1, <span class="kw">aes</span>(<span class="dt">x =</span> .fitted, <span class="dt">y =</span> mpg)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_abline</span>(<span class="dt">intercept =</span> <span class="dv">0</span>, <span class="dt">slope =</span> <span class="dv">1</span>) <span class="op">+</span></span>
<span id="cb38-16"><a href="model-assumptions.html#cb38-16"></a><span class="st">  </span><span class="kw">expand_limits</span>(<span class="dt">x =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">35</span>), <span class="dt">y =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">35</span>)) <span class="op">+</span></span>
<span id="cb38-17"><a href="model-assumptions.html#cb38-17"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Observed vs Fits&quot;</span>,</span>
<span id="cb38-18"><a href="model-assumptions.html#cb38-18"></a>       <span class="dt">subtitle =</span> <span class="st">&quot;Symmetric along 45 degree line?&quot;</span>)</span>
<span id="cb38-19"><a href="model-assumptions.html#cb38-19"></a>p1d &lt;-<span class="st"> </span><span class="kw">ggplot</span>(d1, <span class="kw">aes</span>(<span class="dt">x =</span> hp, <span class="dt">y =</span> .resid)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_abline</span>(<span class="dt">intercept =</span> <span class="dv">0</span>, <span class="dt">slope =</span> <span class="dv">0</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb38-20"><a href="model-assumptions.html#cb38-20"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Residuals vs IV&quot;</span>,</span>
<span id="cb38-21"><a href="model-assumptions.html#cb38-21"></a>       <span class="dt">subtitle =</span> <span class="st">&quot;Random scatter?&quot;</span>)</span>
<span id="cb38-22"><a href="model-assumptions.html#cb38-22"></a><span class="kw">grid.arrange</span>(p1a, p1b, p1c, p1d, <span class="dt">nrow =</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="model-assumptions.html#cb40-1"></a><span class="kw">postResample</span>(<span class="dt">pred =</span> m1<span class="op">$</span>fitted.values, <span class="dt">obs =</span> m1<span class="op">$</span>model<span class="op">$</span>mpg)</span></code></pre></div>
<pre><code>##      RMSE  Rsquared       MAE 
## 3.1366261 0.7204118 2.4074705</code></pre>
<p><img src="data-sci_files/figure-html/unnamed-chunk-12-4.png" width="672" /></p>
</div>
<div id="multicollinearity" class="section level3">
<h3><span class="header-section-number">5.3.2</span> Multicollinearity</h3>
<p>The multicollinearity condition is violated when two or more of the predictors in a regression model are correlated. Muticollinearity can occur for <em>structural</em> reasons, as when one variable is a transformation of another variable, or for <em>data</em> reasons, as occurs in observational studies. Multicollinearity is a problem because it inflates the variances of the estimated coefficients, resulting in larger confidence intervals.</p>
<p>When predictor variables are correlated, the precision of the estimated regression coefficients decreases with each added correlated predictor variable. The usual interpretation of a slope coefficient as the change in the mean response for each additional unit increase in the predictor when all the other predictors are held constant breaks down because changing one predictor necessarily changes the others.</p>
<p>A residuals vs fits plot <span class="math inline">\((\epsilon \sim \hat{Y})\)</span> should have correlation <span class="math inline">\(\rho \sim 0\)</span>. A correlation matrix is helpful for picking out the correlation strengths. A good rule of thumb is correlation coefficients should be less than 0.80. However, this test may not work when a variable is correlated with a function of other variables. A model with multicollinearity may have a significant F-test with insignificant individual slope estimator t-tests. Another way to detect multicollinearity is by calculating variance inflation factors. The predictor variance <span class="math inline">\(Var(\hat{\beta_k})\)</span> increases by a factor</p>
<p><span class="math display">\[VIF_k = \frac{1}{1 - R_k^2}\]</span></p>
<p>where <span class="math inline">\(R_k^2\)</span> is the <span class="math inline">\(R^2\)</span> of a regression of the <span class="math inline">\(k^{th}\)</span> predictor on the remaining predictors. A <span class="math inline">\(VIF_k\)</span> of <span class="math inline">\(1\)</span> indicates no inflation (no corellation). A <span class="math inline">\(VIF_k &gt;= 4\)</span> warrants investigation. A <span class="math inline">\(VIF_k &gt;= 10\)</span> requires correction.</p>
<div id="example-1" class="section level4">
<h4><span class="header-section-number">5.3.2.1</span> Example</h4>
<p>Does the model <code>mpg ~ .</code> exhibit multicollinearity?</p>
<p>The correlation matrix above (and presented again below) has several correlated covariates. <code>disp</code> is strongly correlated with <code>wt</code> (r = 0.89) and <code>hp</code> (r = 0.79).</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="model-assumptions.html#cb42-1"></a>m &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> mtcars)</span>
<span id="cb42-2"><a href="model-assumptions.html#cb42-2"></a><span class="kw">corrplot</span>(<span class="kw">cor</span>(<span class="kw">subset</span>(d, <span class="dt">select =</span> <span class="kw">c</span>(mpg, disp, hp, drat, wt, qsec))), <span class="dt">type =</span> <span class="st">&quot;upper&quot;</span>, <span class="dt">method =</span> <span class="st">&quot;number&quot;</span>)</span></code></pre></div>
<p><img src="data-sci_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>Calculate the VIFs.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="model-assumptions.html#cb43-1"></a><span class="kw">round</span>(<span class="kw">vif</span>(m), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb 
## 15.37 21.62  9.83  3.37 15.16  7.53  4.97  4.65  5.36  7.91</code></pre>
<p>There are two predictors with VIFs greater than 10, cyl (GVIF = 21.36) and disp (GVIF = 13.76). One way to address multicollinearity is removing one or more of the violating predictors from the regression model. Try removing <code>cyl</code>.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="model-assumptions.html#cb45-1"></a><span class="kw">vif</span>(m &lt;-<span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>cyl, <span class="dt">data =</span> d[,<span class="dv">1</span><span class="op">:</span><span class="dv">9</span>]))</span></code></pre></div>
<pre><code>##     disp       hp     drat       wt     qsec       vs       am 
## 9.865991 5.448912 2.818949 7.598119 5.979588 4.249244 3.450410</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="model-assumptions.html#cb47-1"></a><span class="kw">summary</span>(m)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ . - cyl, data = d[, 1:9])
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.4067 -1.4690 -0.2824  1.1415  4.5365 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept) 12.49805   12.48039   1.001  0.32662   
## disp         0.01374    0.01136   1.210  0.23821   
## hp          -0.02282    0.01526  -1.496  0.14778   
## drat         0.95533    1.40737   0.679  0.50376   
## wt          -3.94974    1.26261  -3.128  0.00457 **
## qsec         0.87149    0.61331   1.421  0.16819   
## vsS          0.59017    1.83303   0.322  0.75027   
## ammanual     3.02402    1.66840   1.813  0.08244 . 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.495 on 24 degrees of freedom
## Multiple R-squared:  0.8673,	Adjusted R-squared:  0.8286 
## F-statistic:  22.4 on 7 and 24 DF,  p-value: 4.532e-09</code></pre>
<p>Removing <code>cyl</code> reduced the VIFs of the other variables below 10. <code>disp</code> is still right up there (VIF = 9.87), so it may be worth dropping it from the model too. The model summary still shows that there is only one significant (at .05 level a significance) variable (<code>wt</code>, p = .00457). What if I drop <code>disp</code> too?</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="model-assumptions.html#cb49-1"></a><span class="kw">vif</span>(m &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>cyl <span class="op">-</span><span class="st"> </span>disp, <span class="dt">data =</span> d[,<span class="dv">1</span><span class="op">:</span><span class="dv">9</span>]))</span></code></pre></div>
<pre><code>##       hp     drat       wt     qsec       vs       am 
## 5.070665 2.709905 5.105979 5.776361 4.120656 3.272177</code></pre>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="model-assumptions.html#cb51-1"></a><span class="kw">summary</span>(m)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ . - cyl - disp, data = d[, 1:9])
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.3686 -1.7207 -0.2528  1.0986  4.6029 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept) 16.14103   12.22322   1.321  0.19862   
## hp          -0.01796    0.01486  -1.209  0.23801   
## drat         0.62051    1.39261   0.446  0.65974   
## wt          -3.07506    1.04458  -2.944  0.00691 **
## qsec         0.73472    0.60836   1.208  0.23846   
## vsS          0.20446    1.82173   0.112  0.91153   
## ammanual     2.56534    1.63972   1.565  0.13027   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.518 on 25 degrees of freedom
## Multiple R-squared:  0.8592,	Adjusted R-squared:  0.8254 
## F-statistic: 25.42 on 6 and 25 DF,  p-value: 1.688e-09</code></pre>
<p>The model is not improved, so keep <code>disp</code>.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="model-assumptions.html#cb53-1"></a>m &lt;-<span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>cyl, <span class="dt">data =</span> d[,<span class="dv">1</span><span class="op">:</span><span class="dv">9</span>])</span></code></pre></div>
<p>If the multicollinearity occurs because you are using a polynomial regression model, <em>center</em> the predictor variables (subtract their means).</p>
</div>
<div id="example-2" class="section level4">
<h4><span class="header-section-number">5.3.2.2</span> Example</h4>
<p>Data set <code>exerimmun</code> (<a href="https://newonlinecourses.science.psu.edu/stat501/sites/onlinecourses.science.psu.edu.stat501/files/data/exerimmun/index.txt">exerimun.txt</a>) contains observations of immunoglobin in blood (a measure of immunity) and maximal oxygen uptake (a measure of exercise level) for <span class="math inline">\(n = 30\)</span> individuals.</p>
<ul>
<li><code>igg</code> = amount of immunoglobin in blood (mg)</li>
<li><code>oxygent</code> = maximal oxygen uptake (ml/kg)</li>
</ul>
<p>How does exercise affect the immune system?</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="model-assumptions.html#cb54-1"></a><span class="co">#exerimmun &lt;- read_tsv(file = &quot;./Data/exerimmun.txt&quot;)</span></span>
<span id="cb54-2"><a href="model-assumptions.html#cb54-2"></a>exerimmun &lt;-<span class="st"> </span><span class="kw">tribble</span>(</span>
<span id="cb54-3"><a href="model-assumptions.html#cb54-3"></a>  <span class="op">~</span>igg, <span class="op">~</span>oxygen,</span>
<span id="cb54-4"><a href="model-assumptions.html#cb54-4"></a>  <span class="dv">881</span>,	<span class="fl">34.6</span>,</span>
<span id="cb54-5"><a href="model-assumptions.html#cb54-5"></a>  <span class="dv">1290</span>,	<span class="dv">45</span>,</span>
<span id="cb54-6"><a href="model-assumptions.html#cb54-6"></a>  <span class="dv">2147</span>,	<span class="fl">62.3</span>,</span>
<span id="cb54-7"><a href="model-assumptions.html#cb54-7"></a>  <span class="dv">1909</span>,	<span class="fl">58.9</span>,</span>
<span id="cb54-8"><a href="model-assumptions.html#cb54-8"></a>  <span class="dv">1282</span>,	<span class="fl">42.5</span>,</span>
<span id="cb54-9"><a href="model-assumptions.html#cb54-9"></a>  <span class="dv">1530</span>,	<span class="fl">44.3</span>,</span>
<span id="cb54-10"><a href="model-assumptions.html#cb54-10"></a>  <span class="dv">2067</span>,	<span class="fl">67.9</span>,</span>
<span id="cb54-11"><a href="model-assumptions.html#cb54-11"></a>  <span class="dv">1982</span>,	<span class="fl">58.5</span>,</span>
<span id="cb54-12"><a href="model-assumptions.html#cb54-12"></a>  <span class="dv">1019</span>,	<span class="fl">35.6</span>,</span>
<span id="cb54-13"><a href="model-assumptions.html#cb54-13"></a>  <span class="dv">1651</span>,	<span class="fl">49.6</span>,</span>
<span id="cb54-14"><a href="model-assumptions.html#cb54-14"></a>  <span class="dv">752</span>,	<span class="dv">33</span>,</span>
<span id="cb54-15"><a href="model-assumptions.html#cb54-15"></a>  <span class="dv">1687</span>,	<span class="dv">52</span>,</span>
<span id="cb54-16"><a href="model-assumptions.html#cb54-16"></a>  <span class="dv">1782</span>,	<span class="fl">61.4</span>,</span>
<span id="cb54-17"><a href="model-assumptions.html#cb54-17"></a>  <span class="dv">1529</span>,	<span class="fl">50.2</span>,</span>
<span id="cb54-18"><a href="model-assumptions.html#cb54-18"></a>  <span class="dv">969</span>,	<span class="fl">34.1</span>,</span>
<span id="cb54-19"><a href="model-assumptions.html#cb54-19"></a>  <span class="dv">1660</span>,	<span class="fl">52.5</span>,</span>
<span id="cb54-20"><a href="model-assumptions.html#cb54-20"></a>  <span class="dv">2121</span>,	<span class="fl">69.9</span>,</span>
<span id="cb54-21"><a href="model-assumptions.html#cb54-21"></a>  <span class="dv">1382</span>,	<span class="fl">38.8</span>,</span>
<span id="cb54-22"><a href="model-assumptions.html#cb54-22"></a>  <span class="dv">1714</span>,	<span class="fl">50.6</span>,</span>
<span id="cb54-23"><a href="model-assumptions.html#cb54-23"></a>  <span class="dv">1959</span>,	<span class="fl">69.4</span>,</span>
<span id="cb54-24"><a href="model-assumptions.html#cb54-24"></a>  <span class="dv">1158</span>,	<span class="fl">37.4</span>,</span>
<span id="cb54-25"><a href="model-assumptions.html#cb54-25"></a>  <span class="dv">965</span>,	<span class="fl">35.1</span>,</span>
<span id="cb54-26"><a href="model-assumptions.html#cb54-26"></a>  <span class="dv">1456</span>,	<span class="dv">43</span>,</span>
<span id="cb54-27"><a href="model-assumptions.html#cb54-27"></a>  <span class="dv">1273</span>,	<span class="fl">44.1</span>,</span>
<span id="cb54-28"><a href="model-assumptions.html#cb54-28"></a>  <span class="dv">1418</span>,	<span class="fl">49.8</span>,</span>
<span id="cb54-29"><a href="model-assumptions.html#cb54-29"></a>  <span class="dv">1743</span>,	<span class="fl">54.4</span>,</span>
<span id="cb54-30"><a href="model-assumptions.html#cb54-30"></a>  <span class="dv">1997</span>,	<span class="fl">68.5</span>,</span>
<span id="cb54-31"><a href="model-assumptions.html#cb54-31"></a>  <span class="dv">2177</span>,	<span class="fl">69.5</span>,</span>
<span id="cb54-32"><a href="model-assumptions.html#cb54-32"></a>  <span class="dv">1965</span>,	<span class="dv">63</span>,</span>
<span id="cb54-33"><a href="model-assumptions.html#cb54-33"></a>  <span class="dv">1264</span>,	<span class="fl">43.2</span></span>
<span id="cb54-34"><a href="model-assumptions.html#cb54-34"></a>)</span>
<span id="cb54-35"><a href="model-assumptions.html#cb54-35"></a><span class="kw">head</span>(exerimmun)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##     igg oxygen
##   &lt;dbl&gt;  &lt;dbl&gt;
## 1   881   34.6
## 2  1290   45  
## 3  2147   62.3
## 4  1909   58.9
## 5  1282   42.5
## 6  1530   44.3</code></pre>
<p>The scatterplot <code>oxygen ~ igg</code> shows some curvature. Formulate a quadratic polynomial regression function, <span class="math inline">\(igg_i = \beta_0 + \beta_1 oxygen_i + \beta_2 oxygen_i^2 + \epsilon_i\)</span> where the error terms are assumed to be independent, and normally distributed with equal variance.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="model-assumptions.html#cb56-1"></a><span class="kw">ggplot</span>(exerimmun, <span class="kw">aes</span>(<span class="dt">y =</span> igg, <span class="dt">x =</span> oxygen)) <span class="op">+</span></span>
<span id="cb56-2"><a href="model-assumptions.html#cb56-2"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb56-3"><a href="model-assumptions.html#cb56-3"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> lm, <span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span><span class="kw">poly</span>(x, <span class="dv">2</span>), <span class="dt">se =</span> <span class="ot">FALSE</span>) <span class="op">+</span></span>
<span id="cb56-4"><a href="model-assumptions.html#cb56-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Immunoglobin in Blood&quot;</span>)</span></code></pre></div>
<p><img src="data-sci_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>The formulated regression fits the data well (<span class="math inline">\(adj R^2 = .933\)</span>), but the terms <code>oxygen</code> and <code>oxygen^2</code> are strongly correlated.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="model-assumptions.html#cb57-1"></a>m_blood &lt;-<span class="st"> </span><span class="kw">lm</span>(igg <span class="op">~</span><span class="st"> </span><span class="kw">poly</span>(oxygen, <span class="dv">2</span>), <span class="dt">data =</span> exerimmun)</span>
<span id="cb57-2"><a href="model-assumptions.html#cb57-2"></a><span class="kw">summary</span>(m_blood)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = igg ~ poly(oxygen, 2), data = exerimmun)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -185.375  -82.129    1.047   66.007  227.377 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       1557.63      19.43   80.16  &lt; 2e-16 ***
## poly(oxygen, 2)1  2114.72     106.43   19.87  &lt; 2e-16 ***
## poly(oxygen, 2)2  -360.78     106.43   -3.39  0.00217 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 106.4 on 27 degrees of freedom
## Multiple R-squared:  0.9377,	Adjusted R-squared:  0.9331 
## F-statistic: 203.2 on 2 and 27 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="model-assumptions.html#cb59-1"></a><span class="kw">cor</span>(exerimmun<span class="op">$</span>oxygen, exerimmun<span class="op">$</span>oxygen<span class="op">^</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 0.9949846</code></pre>
<p>Remove the structural multicollinearity by centering the predictors. You can scale the predictors with <code>scale()</code>, but be careful to scale new data when predicting new observations with <code>predict(newdata=)</code>! Whenever possible, perform the transformation right in the model.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="model-assumptions.html#cb61-1"></a>m_blood &lt;-<span class="st"> </span><span class="kw">lm</span>(igg <span class="op">~</span><span class="st"> </span><span class="kw">I</span>(oxygen <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(exerimmun<span class="op">$</span>oxygen)) <span class="op">+</span></span>
<span id="cb61-2"><a href="model-assumptions.html#cb61-2"></a><span class="st">                </span><span class="kw">I</span>((oxygen <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(exerimmun<span class="op">$</span>oxygen))<span class="op">^</span><span class="dv">2</span>), </span>
<span id="cb61-3"><a href="model-assumptions.html#cb61-3"></a>              <span class="dt">data =</span> exerimmun)</span>
<span id="cb61-4"><a href="model-assumptions.html#cb61-4"></a><span class="kw">summary</span>(m_blood)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = igg ~ I(oxygen - mean(exerimmun$oxygen)) + I((oxygen - 
##     mean(exerimmun$oxygen))^2), data = exerimmun)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -185.375  -82.129    1.047   66.007  227.377 
## 
## Coefficients:
##                                         Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)                            1632.1962    29.3486   55.61  &lt; 2e-16
## I(oxygen - mean(exerimmun$oxygen))       33.9995     1.6890   20.13  &lt; 2e-16
## I((oxygen - mean(exerimmun$oxygen))^2)   -0.5362     0.1582   -3.39  0.00217
##                                           
## (Intercept)                            ***
## I(oxygen - mean(exerimmun$oxygen))     ***
## I((oxygen - mean(exerimmun$oxygen))^2) ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 106.4 on 27 degrees of freedom
## Multiple R-squared:  0.9377,	Adjusted R-squared:  0.9331 
## F-statistic: 203.2 on 2 and 27 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The estimated intercept coefficient <span class="math inline">\(\hat{\beta}_0 = 1632\)</span> means a person whose maximal oxygen uptake is <span class="math inline">\(50.64\)</span> ml/kg (the mean value) is predicted to have <span class="math inline">\(1632\)</span> mg of immunoglobin in his blood. The estimated coefficient <span class="math inline">\(\hat{\beta}_1 = 34.0\)</span> means a person whose maximal oxygen uptake is near <span class="math inline">\(50.64\)</span> ml/kg is predicted to increase by 34.0 mg for every 1 ml/kg increase in maximal oxygen uptake.</p>
<p>By performing all transformations in the model, it is straightforward to perform predictions. Here is the predicted value of immunoglobin when maximal oxygen uptake = 90.00 ml/kg.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="model-assumptions.html#cb63-1"></a><span class="kw">predict</span>(m_blood, <span class="dt">newdata =</span> <span class="kw">data.frame</span>(<span class="dt">oxygen =</span> <span class="dv">90</span>), <span class="dt">interval =</span> <span class="st">&quot;prediction&quot;</span>)</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 2139.632 1639.597 2639.666</code></pre>
</div>
</div>
<div id="normality" class="section level3">
<h3><span class="header-section-number">5.3.3</span> Normality</h3>
<p>A normal probability plot or a normal quantile plot should have values near the line with no bow-shaped deviations. A histogram should be normally distributed. A residuals vs fits plot <span class="math inline">\((\epsilon \sim \hat{Y})\)</span> should be randomly scattered around 0. Sometimes the normality check fails when linearity assumption does not hold, so check for linearity first. Parameter estimation is not sensitive to this condition, but prediction intervals are.</p>
</div>
<div id="equal-variances" class="section level3">
<h3><span class="header-section-number">5.3.4</span> Equal Variances</h3>
<p>The residuals should be the same size at both low and high values of the response variable. A residuals vs fits plot <span class="math inline">\((\epsilon \sim \hat{Y})\)</span> should have random scatter in a band of constant width around 0, and no fan shape at the low and high ends. All tests and intervals are sensitive to this condition.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="parameter-estimation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="prediction.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="assets/gitbook-2.6.7/js/app.min.js"></script>
<script src="assets/gitbook-2.6.7/js/lunr.js"></script>
<script src="assets/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="assets/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["data-sci.pdf", "data-sci.epub"],
"toc": {
"collapse": "subsection"
},
"toolbar": {
"position": "static"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
