<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7.3 Ordinal Logistic Regression | My Data Science Notes</title>
  <meta name="description" content="This is a compendium of notes from classes, tutorials, etc. that I reference from time to time." />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="7.3 Ordinal Logistic Regression | My Data Science Notes" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a compendium of notes from classes, tutorials, etc. that I reference from time to time." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7.3 Ordinal Logistic Regression | My Data Science Notes" />
  
  <meta name="twitter:description" content="This is a compendium of notes from classes, tutorials, etc. that I reference from time to time." />
  

<meta name="author" content="Michael Foley" />


<meta name="date" content="2020-04-28" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="multinomial-logistic-regression.html"/>
<link rel="next" href="poisson-regression.html"/>
<script src="assets/jquery-2.2.3/jquery.min.js"></script>
<link href="assets/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">My Data Science Notes</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Intro</a></li>
<li class="chapter" data-level="1" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i><b>1</b> Probability</a><ul>
<li class="chapter" data-level="1.1" data-path="principles.html"><a href="principles.html"><i class="fa fa-check"></i><b>1.1</b> Principles</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="disc-dist.html"><a href="disc-dist.html"><i class="fa fa-check"></i><b>2</b> Discrete Distributions</a><ul>
<li class="chapter" data-level="2.1" data-path="bernoulli.html"><a href="bernoulli.html"><i class="fa fa-check"></i><b>2.1</b> Bernoulli</a></li>
<li class="chapter" data-level="2.2" data-path="binomial.html"><a href="binomial.html"><i class="fa fa-check"></i><b>2.2</b> Binomial</a></li>
<li class="chapter" data-level="2.3" data-path="poission.html"><a href="poission.html"><i class="fa fa-check"></i><b>2.3</b> Poission</a></li>
<li class="chapter" data-level="2.4" data-path="multinomial.html"><a href="multinomial.html"><i class="fa fa-check"></i><b>2.4</b> Multinomial</a></li>
<li class="chapter" data-level="2.5" data-path="negative-binomial.html"><a href="negative-binomial.html"><i class="fa fa-check"></i><b>2.5</b> Negative-Binomial</a></li>
<li class="chapter" data-level="2.6" data-path="geometric.html"><a href="geometric.html"><i class="fa fa-check"></i><b>2.6</b> Geometric</a></li>
<li class="chapter" data-level="2.7" data-path="hypergeometric.html"><a href="hypergeometric.html"><i class="fa fa-check"></i><b>2.7</b> Hypergeometric</a></li>
<li class="chapter" data-level="2.8" data-path="gamma.html"><a href="gamma.html"><i class="fa fa-check"></i><b>2.8</b> Gamma</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="cont-dist.html"><a href="cont-dist.html"><i class="fa fa-check"></i><b>3</b> Continuous Distributions</a><ul>
<li class="chapter" data-level="3.1" data-path="normal.html"><a href="normal.html"><i class="fa fa-check"></i><b>3.1</b> Normal</a><ul>
<li class="chapter" data-level="3.1.1" data-path="normal.html"><a href="normal.html#example-2"><i class="fa fa-check"></i><b>3.1.1</b> Example</a></li>
<li class="chapter" data-level="3.1.2" data-path="normal.html"><a href="normal.html#example-3"><i class="fa fa-check"></i><b>3.1.2</b> Example</a></li>
<li class="chapter" data-level="3.1.3" data-path="normal.html"><a href="normal.html#example-4"><i class="fa fa-check"></i><b>3.1.3</b> Example</a></li>
<li class="chapter" data-level="3.1.4" data-path="normal.html"><a href="normal.html#normal-approximation-to-binomial"><i class="fa fa-check"></i><b>3.1.4</b> Normal Approximation to Binomial</a></li>
<li class="chapter" data-level="3.1.5" data-path="normal.html"><a href="normal.html#example-5"><i class="fa fa-check"></i><b>3.1.5</b> Example</a></li>
<li class="chapter" data-level="3.1.6" data-path="normal.html"><a href="normal.html#example-6"><i class="fa fa-check"></i><b>3.1.6</b> Example</a></li>
<li class="chapter" data-level="3.1.7" data-path="normal.html"><a href="normal.html#from-sample-to-population"><i class="fa fa-check"></i><b>3.1.7</b> From Sample to Population</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="join-distributions.html"><a href="join-distributions.html"><i class="fa fa-check"></i><b>3.2</b> Join Distributions</a></li>
<li class="chapter" data-level="3.3" data-path="likelihood.html"><a href="likelihood.html"><i class="fa fa-check"></i><b>3.3</b> Likelihood</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="discrete-analysis.html"><a href="discrete-analysis.html"><i class="fa fa-check"></i><b>4</b> Categorical Analysis - Nonmodel</a><ul>
<li class="chapter" data-level="4.1" data-path="chi-square-test.html"><a href="chi-square-test.html"><i class="fa fa-check"></i><b>4.1</b> Chi-Square Test</a></li>
<li class="chapter" data-level="4.2" data-path="one-way-tables.html"><a href="one-way-tables.html"><i class="fa fa-check"></i><b>4.2</b> One-Way Tables</a><ul>
<li class="chapter" data-level="4.2.1" data-path="one-way-tables.html"><a href="one-way-tables.html#chi-square-goodness-of-fit-test"><i class="fa fa-check"></i><b>4.2.1</b> Chi-Square Goodness-of-Fit Test</a></li>
<li class="chapter" data-level="4.2.2" data-path="one-way-tables.html"><a href="one-way-tables.html#proportion-test"><i class="fa fa-check"></i><b>4.2.2</b> Proportion Test</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="two-way-tables.html"><a href="two-way-tables.html"><i class="fa fa-check"></i><b>4.3</b> Two-Way Tables</a><ul>
<li class="chapter" data-level="4.3.1" data-path="two-way-tables.html"><a href="two-way-tables.html#chi-square-independence-test"><i class="fa fa-check"></i><b>4.3.1</b> Chi-Square Independence Test</a></li>
<li class="chapter" data-level="4.3.2" data-path="two-way-tables.html"><a href="two-way-tables.html#residuals-analysis"><i class="fa fa-check"></i><b>4.3.2</b> Residuals Analysis</a></li>
<li class="chapter" data-level="4.3.3" data-path="two-way-tables.html"><a href="two-way-tables.html#difference-in-proportions"><i class="fa fa-check"></i><b>4.3.3</b> Difference in Proportions</a></li>
<li class="chapter" data-level="4.3.4" data-path="two-way-tables.html"><a href="two-way-tables.html#relative-risk"><i class="fa fa-check"></i><b>4.3.4</b> Relative Risk</a></li>
<li class="chapter" data-level="4.3.5" data-path="two-way-tables.html"><a href="two-way-tables.html#odds-ratio"><i class="fa fa-check"></i><b>4.3.5</b> Odds Ratio</a></li>
<li class="chapter" data-level="4.3.6" data-path="two-way-tables.html"><a href="two-way-tables.html#partitioning-chi-square"><i class="fa fa-check"></i><b>4.3.6</b> Partitioning Chi-Square</a></li>
<li class="chapter" data-level="4.3.7" data-path="two-way-tables.html"><a href="two-way-tables.html#correlation"><i class="fa fa-check"></i><b>4.3.7</b> Correlation</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="k-way-tables.html"><a href="k-way-tables.html"><i class="fa fa-check"></i><b>4.4</b> K-Way Tables</a><ul>
<li class="chapter" data-level="4.4.1" data-path="k-way-tables.html"><a href="k-way-tables.html#odds-ratio-1"><i class="fa fa-check"></i><b>4.4.1</b> Odds Ratio</a></li>
<li class="chapter" data-level="4.4.2" data-path="k-way-tables.html"><a href="k-way-tables.html#chi-square-independence-test-1"><i class="fa fa-check"></i><b>4.4.2</b> Chi-Square Independence Test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="continuous-analysis.html"><a href="continuous-analysis.html"><i class="fa fa-check"></i><b>5</b> Continuous Variable Analysis</a><ul>
<li class="chapter" data-level="5.0.1" data-path="continuous-analysis.html"><a href="continuous-analysis.html#correlation-1"><i class="fa fa-check"></i><b>5.0.1</b> Correlation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="supervised-machine-learning.html"><a href="supervised-machine-learning.html"><i class="fa fa-check"></i>Supervised Machine Learning</a></li>
<li class="chapter" data-level="6" data-path="ordinary-least-squares.html"><a href="ordinary-least-squares.html"><i class="fa fa-check"></i><b>6</b> Ordinary Least Squares</a><ul>
<li class="chapter" data-level="6.1" data-path="linear-regression-model.html"><a href="linear-regression-model.html"><i class="fa fa-check"></i><b>6.1</b> Linear Regression Model</a></li>
<li class="chapter" data-level="6.2" data-path="parameter-estimation.html"><a href="parameter-estimation.html"><i class="fa fa-check"></i><b>6.2</b> Parameter Estimation</a></li>
<li class="chapter" data-level="6.3" data-path="model-assumptions.html"><a href="model-assumptions.html"><i class="fa fa-check"></i><b>6.3</b> Model Assumptions</a><ul>
<li class="chapter" data-level="6.3.1" data-path="model-assumptions.html"><a href="model-assumptions.html#linearity"><i class="fa fa-check"></i><b>6.3.1</b> Linearity</a></li>
<li class="chapter" data-level="6.3.2" data-path="model-assumptions.html"><a href="model-assumptions.html#multicollinearity"><i class="fa fa-check"></i><b>6.3.2</b> Multicollinearity</a></li>
<li class="chapter" data-level="6.3.3" data-path="model-assumptions.html"><a href="model-assumptions.html#normality"><i class="fa fa-check"></i><b>6.3.3</b> Normality</a></li>
<li class="chapter" data-level="6.3.4" data-path="model-assumptions.html"><a href="model-assumptions.html#equal-variances"><i class="fa fa-check"></i><b>6.3.4</b> Equal Variances</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="prediction.html"><a href="prediction.html"><i class="fa fa-check"></i><b>6.4</b> Prediction</a></li>
<li class="chapter" data-level="6.5" data-path="inference.html"><a href="inference.html"><i class="fa fa-check"></i><b>6.5</b> Inference</a><ul>
<li class="chapter" data-level="6.5.1" data-path="inference.html"><a href="inference.html#t-test"><i class="fa fa-check"></i><b>6.5.1</b> <em>t</em>-Test</a></li>
<li class="chapter" data-level="6.5.2" data-path="inference.html"><a href="inference.html#f-test"><i class="fa fa-check"></i><b>6.5.2</b> <em>F</em>-Test</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="interpretation.html"><a href="interpretation.html"><i class="fa fa-check"></i><b>6.6</b> Interpretation</a></li>
<li class="chapter" data-level="6.7" data-path="model-validation.html"><a href="model-validation.html"><i class="fa fa-check"></i><b>6.7</b> Model Validation</a><ul>
<li class="chapter" data-level="6.7.1" data-path="model-validation.html"><a href="model-validation.html#accuracy-metrics"><i class="fa fa-check"></i><b>6.7.1</b> Accuracy Metrics</a></li>
<li class="chapter" data-level="6.7.2" data-path="model-validation.html"><a href="model-validation.html#cross-validation"><i class="fa fa-check"></i><b>6.7.2</b> Cross-Validation</a></li>
<li class="chapter" data-level="6.7.3" data-path="model-validation.html"><a href="model-validation.html#gain-curve"><i class="fa fa-check"></i><b>6.7.3</b> Gain Curve</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="reference.html"><a href="reference.html"><i class="fa fa-check"></i><b>6.8</b> Reference</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html"><i class="fa fa-check"></i><b>7</b> Generalized Linear Models</a><ul>
<li class="chapter" data-level="7.1" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>7.1</b> Logistic Regression</a></li>
<li class="chapter" data-level="7.2" data-path="multinomial-logistic-regression.html"><a href="multinomial-logistic-regression.html"><i class="fa fa-check"></i><b>7.2</b> Multinomial Logistic Regression</a></li>
<li class="chapter" data-level="7.3" data-path="ordinal-logistic-regression.html"><a href="ordinal-logistic-regression.html"><i class="fa fa-check"></i><b>7.3</b> Ordinal Logistic Regression</a><ul>
<li class="chapter" data-level="7.3.1" data-path="ordinal-logistic-regression.html"><a href="ordinal-logistic-regression.html#assumptions"><i class="fa fa-check"></i><b>7.3.1</b> Assumptions</a></li>
<li class="chapter" data-level="7.3.2" data-path="ordinal-logistic-regression.html"><a href="ordinal-logistic-regression.html#modeling"><i class="fa fa-check"></i><b>7.3.2</b> Modeling</a></li>
<li class="chapter" data-level="7.3.3" data-path="ordinal-logistic-regression.html"><a href="ordinal-logistic-regression.html#case-study"><i class="fa fa-check"></i><b>7.3.3</b> Case Study</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="poisson-regression.html"><a href="poisson-regression.html"><i class="fa fa-check"></i><b>7.4</b> Poisson Regression</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="linear-discriminant-analysis.html"><a href="linear-discriminant-analysis.html"><i class="fa fa-check"></i><b>8</b> Linear Discriminant Analysis</a></li>
<li class="chapter" data-level="9" data-path="classification.html"><a href="classification.html"><i class="fa fa-check"></i><b>9</b> Classification</a></li>
<li class="chapter" data-level="10" data-path="regularization.html"><a href="regularization.html"><i class="fa fa-check"></i><b>10</b> Regularization</a></li>
<li class="chapter" data-level="11" data-path="decision-trees.html"><a href="decision-trees.html"><i class="fa fa-check"></i><b>11</b> Decision Trees</a><ul>
<li class="chapter" data-level="11.1" data-path="classification-tree.html"><a href="classification-tree.html"><i class="fa fa-check"></i><b>11.1</b> Classification Tree</a><ul>
<li class="chapter" data-level="11.1.1" data-path="classification-tree.html"><a href="classification-tree.html#confusion-matrix"><i class="fa fa-check"></i><b>11.1.1</b> Confusion Matrix</a></li>
<li class="chapter" data-level="11.1.2" data-path="classification-tree.html"><a href="classification-tree.html#roc-curve"><i class="fa fa-check"></i><b>11.1.2</b> ROC Curve</a></li>
<li class="chapter" data-level="11.1.3" data-path="classification-tree.html"><a href="classification-tree.html#caret-approach"><i class="fa fa-check"></i><b>11.1.3</b> Caret Approach</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="regression-trees.html"><a href="regression-trees.html"><i class="fa fa-check"></i><b>11.2</b> Regression Trees</a><ul>
<li class="chapter" data-level="11.2.1" data-path="regression-trees.html"><a href="regression-trees.html#caret-approach-1"><i class="fa fa-check"></i><b>11.2.1</b> Caret Approach</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="bagging.html"><a href="bagging.html"><i class="fa fa-check"></i><b>11.3</b> Bagging</a></li>
<li class="chapter" data-level="11.4" data-path="random-forests.html"><a href="random-forests.html"><i class="fa fa-check"></i><b>11.4</b> Random Forests</a></li>
<li class="chapter" data-level="11.5" data-path="gradient-boosting.html"><a href="gradient-boosting.html"><i class="fa fa-check"></i><b>11.5</b> Gradient Boosting</a></li>
<li class="chapter" data-level="11.6" data-path="summary.html"><a href="summary.html"><i class="fa fa-check"></i><b>11.6</b> Summary</a></li>
<li class="chapter" data-level="11.7" data-path="reference-1.html"><a href="reference-1.html"><i class="fa fa-check"></i><b>11.7</b> Reference</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="non-linear-models.html"><a href="non-linear-models.html"><i class="fa fa-check"></i><b>12</b> Non-linear Models</a><ul>
<li class="chapter" data-level="12.1" data-path="splines.html"><a href="splines.html"><i class="fa fa-check"></i><b>12.1</b> Splines</a></li>
<li class="chapter" data-level="12.2" data-path="mars.html"><a href="mars.html"><i class="fa fa-check"></i><b>12.2</b> MARS</a></li>
<li class="chapter" data-level="12.3" data-path="gam.html"><a href="gam.html"><i class="fa fa-check"></i><b>12.3</b> GAM</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="support-vector-machines.html"><a href="support-vector-machines.html"><i class="fa fa-check"></i><b>13</b> Support Vector Machines</a><ul>
<li class="chapter" data-level="13.1" data-path="maximal-margin-classifier.html"><a href="maximal-margin-classifier.html"><i class="fa fa-check"></i><b>13.1</b> Maximal Margin Classifier</a></li>
<li class="chapter" data-level="13.2" data-path="support-vector-classifier.html"><a href="support-vector-classifier.html"><i class="fa fa-check"></i><b>13.2</b> Support Vector Classifier</a></li>
<li class="chapter" data-level="13.3" data-path="support-vector-machines-1.html"><a href="support-vector-machines-1.html"><i class="fa fa-check"></i><b>13.3</b> Support Vector Machines</a></li>
<li class="chapter" data-level="13.4" data-path="example-16.html"><a href="example-16.html"><i class="fa fa-check"></i><b>13.4</b> Example</a></li>
<li class="chapter" data-level="13.5" data-path="using-caret.html"><a href="using-caret.html"><i class="fa fa-check"></i><b>13.5</b> Using Caret</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="principal-components-analysis.html"><a href="principal-components-analysis.html"><i class="fa fa-check"></i><b>14</b> Principal Components Analysis</a></li>
<li class="chapter" data-level="15" data-path="clustering.html"><a href="clustering.html"><i class="fa fa-check"></i><b>15</b> Clustering</a></li>
<li class="chapter" data-level="16" data-path="text-mining.html"><a href="text-mining.html"><i class="fa fa-check"></i><b>16</b> Text Mining</a></li>
<li class="chapter" data-level="17" data-path="survival-analysis.html"><a href="survival-analysis.html"><i class="fa fa-check"></i><b>17</b> Survival Analysis</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html"><i class="fa fa-check"></i>Appendix</a><ul>
<li class="chapter" data-level="" data-path="publishing-to-bookdown.html"><a href="publishing-to-bookdown.html"><i class="fa fa-check"></i>Publishing to BookDown</a></li>
<li class="chapter" data-level="" data-path="shiny-apps.html"><a href="shiny-apps.html"><i class="fa fa-check"></i>Shiny Apps</a></li>
<li class="chapter" data-level="" data-path="packages.html"><a href="packages.html"><i class="fa fa-check"></i>Packages</a><ul>
<li class="chapter" data-level="" data-path="packages.html"><a href="packages.html#create-a-package"><i class="fa fa-check"></i>Create a package</a></li>
<li class="chapter" data-level="17.0.1" data-path="packages.html"><a href="packages.html#document-functions-with-roxygen"><i class="fa fa-check"></i><b>17.0.1</b> Document Functions with roxygen</a></li>
<li class="chapter" data-level="" data-path="packages.html"><a href="packages.html#create-data"><i class="fa fa-check"></i>Create Data</a></li>
<li class="chapter" data-level="" data-path="packages.html"><a href="packages.html#create-vignette"><i class="fa fa-check"></i>Create Vignette</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">My Data Science Notes</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ordinal-logistic-regression" class="section level2">
<h2><span class="header-section-number">7.3</span> Ordinal Logistic Regression</h2>
<p>These notes rely on <a href="https://data.library.virginia.edu/fitting-and-interpreting-a-proportional-odds-model/">UVA</a>, <a href="https://online.stat.psu.edu/stat504/node/171/">PSU STAT 504 class notes</a>, and <a href="https://statistics.laerd.com/spss-tutorials/ordinal-regression-using-spss-statistics.php">Laerd Statistics</a>.</p>
<p>The ordinal logistic regression model is</p>
<p><span class="math display">\[logit[P(Y \le j)] = \log \left[ \frac{P(Y \le j)}{P(Y \gt j)} \right] = \alpha_j - \beta X, \hspace{5mm} j \in [1, J-1]\]</span>
where <span class="math inline">\(j \in [1, J-1]\)</span> are the levels of the ordinal outcome variable <span class="math inline">\(Y\)</span>. The proportional odds model assumes there is a common set of slope parameters <span class="math inline">\(\beta\)</span> for the predictors. The ordinal outcomes are distinguished by the <span class="math inline">\(J-1\)</span> intercepts <span class="math inline">\(\alpha_j\)</span>. The benchmark level is <span class="math inline">\(J\)</span>.</p>
<p>Technically, the model could be written <span class="math inline">\(logit[P(Y \le j)] = \alpha_j + \zeta X\)</span>, replacing beta with zeta because the model fits <span class="math inline">\(\alpha_j - \beta X\)</span> instead of <span class="math inline">\(\alpha_j + \beta X\)</span>.</p>
<p>Suppose you want to model the probability a respondent holds a political ideology [“Socialist”, “Liberal”, “Moderate”, “Conservative”, “Libertarian”] given their party affiliation [“Republican”, “Democrat”].</p>
<div class="sourceCode" id="cb526"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb526-1"><a href="ordinal-logistic-regression.html#cb526-1"></a><span class="kw">table</span>(ideology)</span></code></pre></div>
<pre><code>##      ideo
## party Socialist Liberal Moderate Conservative Libertarian
##   Rep        30      46      148           84          99
##   Dem        80      81      171           41          55</code></pre>
<div id="assumptions" class="section level3">
<h3><span class="header-section-number">7.3.1</span> Assumptions</h3>
<p>Ordinal regression makes four assumptions about the underlying data. One is that the response variable is ordinal (duh). The second is that the explanatory variables are continuous or categorical. You can include ordinal variables, but you need to treat them either as continous or categorical. Third, there is no multicollinearity. Fourth, the odds are proportional, meaning each independent variable has an identical effect at each cumulative split of the ordinal dependent variable. Test for proportionality with a full likelihood ratio test comparing the fitted location model to a model with varying location parameters. This test can sometimes flag violations that do not exist, so can also run separate binomial logistic regressions on cumulative dichotomous dependent variables to further determine if this assumption is met.</p>
</div>
<div id="modeling" class="section level3">
<h3><span class="header-section-number">7.3.2</span> Modeling</h3>
<p>Fit a proportional odds logistic regression.</p>
<div class="sourceCode" id="cb528"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb528-1"><a href="ordinal-logistic-regression.html#cb528-1"></a>pom &lt;-<span class="st"> </span>MASS<span class="op">::</span><span class="kw">polr</span>(ideo <span class="op">~</span><span class="st"> </span>party, <span class="dt">data =</span> ideology)</span>
<span id="cb528-2"><a href="ordinal-logistic-regression.html#cb528-2"></a><span class="kw">summary</span>(pom)</span></code></pre></div>
<pre><code>## Call:
## MASS::polr(formula = ideo ~ party, data = ideology)
## 
## Coefficients:
##           Value Std. Error t value
## partyDem -0.975      0.129   -7.54
## 
## Intercepts:
##                          Value   Std. Error t value
## Socialist|Liberal         -2.469   0.132    -18.736
## Liberal|Moderate          -1.475   0.109    -13.531
## Moderate|Conservative      0.237   0.094      2.516
## Conservative|Libertarian   1.070   0.104     10.292
## 
## Residual Deviance: 2474.98 
## AIC: 2484.98</code></pre>
<p>The log-odds a Democrat identifies as <em>Socialist</em> vs <em>&gt;Socialist</em>, or equivalently, the log-odds a Democrat identifies as <em>&lt;=Socialist</em> vs <em>&gt;=Liberal</em> is</p>
<p><span class="math display">\[logit[P(Y \le 1)] = -2.4690 - (-0.9745)(1) = -1.4945\]</span></p>
<p>which translates into an odds of</p>
<p><span class="math display">\[odds(Y&lt;=1) = exp(logit[P(Y \le 1)]) = \frac{exp(-2.469)}{exp(-0.9745)} = 0.2244\]</span></p>
<p>It is the same for Republicans, except multiply the slope coefficient by zero.</p>
<p><span class="math display">\[logit[P(Y \le 1)] = -2.4690 - (-0.9745)(0) = -2.4690\]</span></p>
<p><span class="math display">\[odds(Y&lt;=1) = exp(logit[P(Y \le 1)]) = \frac{exp(-2.469)}{exp(0)} = -2.4690\]</span></p>
<p>The “proportional odds” part of the proportional odds model is that the ratios of the <span class="math inline">\(J - 1\)</span> odds are identical for each level of the predictors. The numerators are always the same, and the denominators differ only by the exponent of the slope coefficient, <span class="math inline">\(-0.9745\)</span>. For all <span class="math inline">\(j \in [1, J-1]\)</span>, the odds a Democrat’s ideology is <span class="math inline">\(\le j\)</span> vs <span class="math inline">\(&gt;j\)</span> is <span class="math inline">\(exp(-0.9745) = 2.6498\)</span> times that of a Republican’s odds.</p>
<p>You can translate the cumulative odds to cumulative probabilities by taking the ratio <span class="math inline">\(\pi = exp(odds) / (1 + exp(odds))\)</span>. The probability a Democrat identifies as <em>&lt;=Socialist</em> vs <em>&gt;Socialist</em> is</p>
<p><span class="math display">\[P(Y \le 1) = \frac{exp(-1.4945)} {(1 + exp(-1.4945))} = 0.183.\]</span></p>
<p>The individual probabilities are just the successive differences in the cumulative probabilities. The log odds a Democrat identifies as <em>&lt;=Liberal</em> vs <em>&gt;Liberal</em> are <span class="math inline">\(logit[P(Y \lt 2)] = -1.4745 - (-0.9745)(1) = -0.500\)</span>, which translates into a probability of <span class="math inline">\(P(Y \le 2) = exp(-0.5) / (1 + exp(-0.5)) = 0.378\)</span>. The probability a Democrat identifies as <em>Liberal</em> is the difference in adjacent cumulative probabilities, <span class="math inline">\(P(Y \le 2) - P(Y \le 1) = 0.378 = 0.183 = 0.194\)</span>. This is how the model to predicts the level probabilities.</p>
<div class="sourceCode" id="cb530"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb530-1"><a href="ordinal-logistic-regression.html#cb530-1"></a>x &lt;-<span class="st"> </span><span class="kw">predict</span>(pom, <span class="dt">newdata =</span> <span class="kw">data.frame</span>(<span class="dt">party =</span> <span class="kw">c</span>(<span class="st">&quot;Dem&quot;</span>, <span class="st">&quot;Rep&quot;</span>)), <span class="dt">type =</span> <span class="st">&quot;probs&quot;</span>)</span>
<span id="cb530-2"><a href="ordinal-logistic-regression.html#cb530-2"></a><span class="kw">rownames</span>(x) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Dem&quot;</span>, <span class="st">&quot;Rep&quot;</span>)</span>
<span id="cb530-3"><a href="ordinal-logistic-regression.html#cb530-3"></a><span class="kw">print</span>(x)</span></code></pre></div>
<pre><code>##     Socialist Liberal Moderate Conservative Libertarian
## Dem     0.183    0.19     0.39         0.11        0.11
## Rep     0.078    0.11     0.37         0.19        0.26</code></pre>
<p>Always check the assumption of proportional odds. One way to do this is by comparing the proportional odds model with a multinomial logit model, also called an unconstrained baseline logit model. The multinomial logit model models <em>unordered</em> responses and fits a slope to each level of the <span class="math inline">\(J – 1\)</span> responses. The proportional odds model is nested in the multinomial model, so you can use a likelihood ratio test to see if the models are statistically different.</p>
<div class="sourceCode" id="cb532"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb532-1"><a href="ordinal-logistic-regression.html#cb532-1"></a>mlm &lt;-<span class="st"> </span>nnet<span class="op">::</span><span class="kw">multinom</span>(ideo <span class="op">~</span><span class="st"> </span>party, <span class="dt">data =</span> ideology)</span></code></pre></div>
<pre><code>## # weights:  15 (8 variable)
## initial  value 1343.880657 
## iter  10 value 1239.866743
## final  value 1235.648615 
## converged</code></pre>
<p>Calculate the difference in the deviance test statistics <span class="math inline">\(D = -2 loglik(\beta)\)</span>.</p>
<div class="sourceCode" id="cb534"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb534-1"><a href="ordinal-logistic-regression.html#cb534-1"></a>G &lt;-<span class="st"> </span><span class="dv">-2</span> <span class="op">*</span><span class="st"> </span>(<span class="kw">logLik</span>(pom)[<span class="dv">1</span>] <span class="op">-</span><span class="st"> </span><span class="kw">logLik</span>(mlm)[<span class="dv">1</span>])</span>
<span id="cb534-2"><a href="ordinal-logistic-regression.html#cb534-2"></a><span class="kw">pchisq</span>(G, <span class="dt">df =</span> <span class="kw">length</span>(pom<span class="op">$</span>zeta) <span class="op">-</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<pre><code>## [1] 0.3</code></pre>
<p>The p-value is high, so do not reject the null hypothesis that the proportional odds model fits differently than the more complex multinomial logit model.</p>
</div>
<div id="case-study" class="section level3">
<h3><span class="header-section-number">7.3.3</span> Case Study</h3>
<p>The General Social Survey for <code>year</code> 1972, 1973, and 1974 surveyed caucasian Christians about their attitudes <code>att</code> toward abortion. Respondents were classified by years of education <code>edu</code> and religious group <code>att</code>.</p>
<div class="sourceCode" id="cb536"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb536-1"><a href="ordinal-logistic-regression.html#cb536-1"></a>abort <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pivot_wider</span>(<span class="dt">names_from =</span> att, <span class="dt">values_from =</span> cnt) </span></code></pre></div>
<pre><code>## # A tibble: 27 x 6
##    year  rel   edu     Neg   Mix   Pos
##    &lt;fct&gt; &lt;fct&gt; &lt;fct&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 1972  Prot  Low       9    12    48
##  2 1972  Prot  Med      13    43   197
##  3 1972  Prot  High      4     9   139
##  4 1972  SProt Low       9    17    30
##  5 1972  SProt Med       6    10    97
##  6 1972  SProt High      1     8    68
##  7 1972  Cath  Low      14    12    32
##  8 1972  Cath  Med      18    50   131
##  9 1972  Cath  High      8    13    64
## 10 1973  Prot  Low       4    16    59
## # ... with 17 more rows</code></pre>
<p>Fit a proportional-odds cumulative logit model with just main effects. There are two main effects for <code>year</code>, two for <code>rel</code>, and two for <code>edu</code>, plus two logit equations for the response for a total of eight parameters.</p>
<div class="sourceCode" id="cb538"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb538-1"><a href="ordinal-logistic-regression.html#cb538-1"></a>abort_mdl &lt;-<span class="st"> </span>MASS<span class="op">::</span><span class="kw">polr</span>(att <span class="op">~</span><span class="st"> </span>year <span class="op">+</span><span class="st"> </span>rel <span class="op">+</span><span class="st"> </span>edu, <span class="dt">data =</span> abort, <span class="dt">weights =</span> cnt)</span>
<span id="cb538-2"><a href="ordinal-logistic-regression.html#cb538-2"></a><span class="kw">summary</span>(abort_mdl)</span></code></pre></div>
<pre><code>## Call:
## MASS::polr(formula = att ~ year + rel + edu, data = abort, weights = cnt)
## 
## Coefficients:
##           Value Std. Error t value
## year1973  0.221      0.105    2.11
## year1974  0.233      0.106    2.20
## relSProt -0.249      0.113   -2.19
## relCath  -0.796      0.100   -7.93
## eduMed    0.717      0.109    6.59
## eduHigh   1.127      0.128    8.79
## 
## Intercepts:
##         Value  Std. Error t value
## Neg|Mix  -2.33   0.14     -17.27 
## Mix|Pos  -0.79   0.12      -6.49 
## 
## Residual Deviance: 4059.32 
## AIC: 4075.32</code></pre>
<p>All predictors are significant. Now fit the saturated model.</p>
<div class="sourceCode" id="cb540"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb540-1"><a href="ordinal-logistic-regression.html#cb540-1"></a>abort_mdl_sat &lt;-<span class="st"> </span>MASS<span class="op">::</span><span class="kw">polr</span>(att <span class="op">~</span><span class="st"> </span>year<span class="op">*</span>rel<span class="op">*</span>edu, <span class="dt">weights =</span> cnt, <span class="dt">data =</span> abort)</span>
<span id="cb540-2"><a href="ordinal-logistic-regression.html#cb540-2"></a><span class="kw">summary</span>(abort_mdl_sat)</span></code></pre></div>
<pre><code>## Call:
## MASS::polr(formula = att ~ year * rel * edu, data = abort, weights = cnt)
## 
## Coefficients:
##                             Value Std. Error t value
## year1973                   0.3422      0.365  0.9370
## year1974                  -0.0144      0.361 -0.0398
## relSProt                  -0.6274      0.366 -1.7141
## relCath                   -0.7238      0.369 -1.9620
## eduMed                     0.5036      0.301  1.6743
## eduHigh                    1.6007      0.390  4.1068
## year1973:relSProt          0.1093      0.524  0.2088
## year1974:relSProt          0.4387      0.521  0.8421
## year1973:relCath           0.3895      0.539  0.7228
## year1974:relCath           0.8696      0.559  1.5543
## year1973:eduMed            0.2805      0.441  0.6365
## year1974:eduMed            0.5487      0.430  1.2761
## year1973:eduHigh          -0.5961      0.540 -1.1031
## year1974:eduHigh          -0.1175      0.541 -0.2171
## relSProt:eduMed            1.1421      0.479  2.3849
## relCath:eduMed             0.1275      0.424  0.3004
## relSProt:eduHigh           0.3039      0.586  0.5186
## relCath:eduHigh           -0.5623      0.532 -1.0572
## year1973:relSProt:eduMed  -1.2710      0.667 -1.9069
## year1974:relSProt:eduMed  -1.3331      0.668 -1.9952
## year1973:relCath:eduMed   -0.8360      0.629 -1.3291
## year1974:relCath:eduMed   -0.8973      0.647 -1.3879
## year1973:relSProt:eduHigh  0.9047      0.878  1.0309
## year1974:relSProt:eduHigh -0.4321      0.805 -0.5369
## year1973:relCath:eduHigh  -0.2265      0.749 -0.3021
## year1974:relCath:eduHigh  -0.9896      0.766 -1.2915
## 
## Intercepts:
##         Value  Std. Error t value
## Neg|Mix -2.311  0.267     -8.647 
## Mix|Pos -0.761  0.261     -2.922 
## 
## Residual Deviance: 4018.27 
## AIC: 4074.27</code></pre>
<p>Compare the two models.</p>
<div class="sourceCode" id="cb542"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb542-1"><a href="ordinal-logistic-regression.html#cb542-1"></a><span class="kw">anova</span>(abort_mdl, abort_mdl_sat)</span></code></pre></div>
<pre><code>## Likelihood ratio tests of ordinal regression models
## 
## Response: att
##              Model Resid. df Resid. Dev   Test    Df LR stat. Pr(Chi)
## 1 year + rel + edu      3229       4059                              
## 2 year * rel * edu      3209       4018 1 vs 2    20       41  0.0037</code></pre>
<p>The likelihood ratio test indicates the main-effects model fits poorly in comparison to the saturated model (<em>LR</em> = 41.0, <em>df</em> = 20, <em>p</em> &lt; 0.01). From the table of coefficients,the effects of religion and education appear to be much more powerful than the year, so consider modeling an interaction between <code>rel</code> and <code>edu</code>. This is also what the stepwise AIC algorithm recommends.</p>
<div class="sourceCode" id="cb544"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb544-1"><a href="ordinal-logistic-regression.html#cb544-1"></a><span class="kw">summary</span>(abort_mdl_step)</span></code></pre></div>
<pre><code>## Call:
## MASS::polr(formula = att ~ year + rel + edu + rel:edu, data = abort, 
##     weights = cnt)
## 
## Coefficients:
##                   Value Std. Error t value
## year1973          0.228      0.105   2.171
## year1974          0.241      0.106   2.271
## relSProt         -0.450      0.213  -2.110
## relCath          -0.348      0.223  -1.556
## eduMed            0.750      0.177   4.230
## eduHigh           1.369      0.219   6.244
## relSProt:eduMed   0.253      0.267   0.946
## relCath:eduMed   -0.389      0.260  -1.496
## relSProt:eduHigh  0.385      0.336   1.146
## relCath:eduHigh  -0.944      0.307  -3.079
## 
## Intercepts:
##         Value  Std. Error t value
## Neg|Mix  -2.26   0.17     -13.28 
## Mix|Pos  -0.72   0.16      -4.49 
## 
## Residual Deviance: 4040.44 
## AIC: 4064.44</code></pre>
<p>Compare the model with the <code>rel:edu</code> interaction to the saturated model.</p>
<div class="sourceCode" id="cb546"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb546-1"><a href="ordinal-logistic-regression.html#cb546-1"></a><span class="kw">anova</span>(abort_mdl_step, abort_mdl_sat)</span></code></pre></div>
<pre><code>## Likelihood ratio tests of ordinal regression models
## 
## Response: att
##                        Model Resid. df Resid. Dev   Test    Df LR stat. Pr(Chi)
## 1 year + rel + edu + rel:edu      3225       4040                              
## 2           year * rel * edu      3209       4018 1 vs 2    16       22    0.14</code></pre>
<p>Great, this time they are not significantly different (<em>LR</em> = 22.2, <em>df</em> = 16, <em>p</em> = 0.138). Interpret the results.</p>
<p>Positive coefficients mean attitudes toward legalizing abortion are more positive relative to the reference year, 1972. The odds of supporting legalization in 1973 compared to 1972 were <span class="math inline">\(exp(0.2281) = 1.26\)</span>. The odds for 1974 vs 1972 were <span class="math inline">\(exp(0.2410) = 1.27\)</span>, so attitudes toward abortion became more positive from 1972 to 1973, but remained nearly unchanged from 1973 to 1974.</p>
<p>Among Protestants (reference religious group), increasing education is associated with more positive attitudes toward abortion legalization. The odds of a Protestant with medium education vs low education supporting legalization are <span class="math inline">\(exp(0.7504) = 2.12\)</span>. Among Southern Protestants, odds are <span class="math inline">\(exp(0.7504 + 0.2526) = 2.73\)</span>. Therefore, the estimated effects of education for Southern Protestants are in the same direction as for Protestants but are somewhat larger. Note, however, that the interaction effect coefficient is not not significantly different from zero, so the effect of education among Protestants and Southern Protestants is not significantly different.</p>
<p>Among Catholics, the medium vs low education odds are <span class="math inline">\(exp(0.7504- 0.3892) = 1.44\)</span>. And the high vs low education odds are <span class="math inline">\(exp(1.3689 - 0.9442) = 1.53\)</span>. Increasing education is still associated with more positive attitudes, but the effects are smaller than they are among Protestants and Southern Protestants.</p>
<p><img src="data-sci_files/figure-html/unnamed-chunk-249-1.png" width="672" /></p>
<p><strong>Example Summarization</strong></p>
<p>We used logistic regression to investigate whether groups with the Christian religion might moderate the effects of education on attitudes toward abortion legalization. For Protestants, higher education education was associated with higher, significant, increase of odds of a more positive attitude toward abortion legalization, <em>b</em> = 0.7504, <em>SE</em> = 0.1774, <em>OR</em> = 2.12, <em>p</em> &lt; .01. There was a significant interaction for Catholics at high levels of education, <em>b</em> = -0.9442, <em>SE</em> = 0.3066, <em>p</em> &lt; .01, relative to the Protestant reference group, but no significant interaction at medium education, and no interaction at all for Southern Protestants relative to the reference group. The figure above graphs the interaction, showing the change in the expected probability of positive attitude by education level for Protestant, Southern Protestant, and Catholic religious groups. Overall, the significant interaction for Catholics at high levels of education suggests that education has a different relationship to attitudes toward abortion depending on the individual’s religious group, but the difference between Protestant and Southern Protestant is minimal.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="multinomial-logistic-regression.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="poisson-regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="assets/gitbook-2.6.7/js/app.min.js"></script>
<script src="assets/gitbook-2.6.7/js/lunr.js"></script>
<script src="assets/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="assets/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["data-sci.pdf", "data-sci.epub"],
"toc": {
"collapse": "subsection"
},
"toolbar": {
"position": "static"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
