<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>15.2 Survival Curve Estimation | My Data Science Notes</title>
  <meta name="description" content="This is a compendium of notes from classes, tutorials, etc. that I reference from time to time." />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="15.2 Survival Curve Estimation | My Data Science Notes" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a compendium of notes from classes, tutorials, etc. that I reference from time to time." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="15.2 Survival Curve Estimation | My Data Science Notes" />
  
  <meta name="twitter:description" content="This is a compendium of notes from classes, tutorials, etc. that I reference from time to time." />
  

<meta name="author" content="Michael Foley" />


<meta name="date" content="2020-06-03" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="basic-concepts.html"/>
<link rel="next" href="appendix.html"/>
<script src="assets/jquery-2.2.3/jquery.min.js"></script>
<link href="assets/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">My Data Science Notes</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Intro</a></li>
<li class="chapter" data-level="1" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i><b>1</b> Probability</a><ul>
<li class="chapter" data-level="1.1" data-path="principles.html"><a href="principles.html"><i class="fa fa-check"></i><b>1.1</b> Principles</a></li>
<li class="chapter" data-level="1.2" data-path="disc-dist.html"><a href="disc-dist.html"><i class="fa fa-check"></i><b>1.2</b> Discrete Distributions</a><ul>
<li class="chapter" data-level="1.2.1" data-path="disc-dist.html"><a href="disc-dist.html#bernoulli"><i class="fa fa-check"></i><b>1.2.1</b> Bernoulli</a></li>
<li class="chapter" data-level="1.2.2" data-path="disc-dist.html"><a href="disc-dist.html#binomial"><i class="fa fa-check"></i><b>1.2.2</b> Binomial</a></li>
<li class="chapter" data-level="1.2.3" data-path="disc-dist.html"><a href="disc-dist.html#poission"><i class="fa fa-check"></i><b>1.2.3</b> Poission</a></li>
<li class="chapter" data-level="1.2.4" data-path="disc-dist.html"><a href="disc-dist.html#multinomial"><i class="fa fa-check"></i><b>1.2.4</b> Multinomial</a></li>
<li class="chapter" data-level="1.2.5" data-path="disc-dist.html"><a href="disc-dist.html#negative-binomial"><i class="fa fa-check"></i><b>1.2.5</b> Negative-Binomial</a></li>
<li class="chapter" data-level="1.2.6" data-path="disc-dist.html"><a href="disc-dist.html#geometric"><i class="fa fa-check"></i><b>1.2.6</b> Geometric</a></li>
<li class="chapter" data-level="1.2.7" data-path="disc-dist.html"><a href="disc-dist.html#hypergeometric"><i class="fa fa-check"></i><b>1.2.7</b> Hypergeometric</a></li>
<li class="chapter" data-level="1.2.8" data-path="disc-dist.html"><a href="disc-dist.html#gamma"><i class="fa fa-check"></i><b>1.2.8</b> Gamma</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="cont-dist.html"><a href="cont-dist.html"><i class="fa fa-check"></i><b>1.3</b> Continuous Distributions</a><ul>
<li class="chapter" data-level="1.3.1" data-path="cont-dist.html"><a href="cont-dist.html#normal"><i class="fa fa-check"></i><b>1.3.1</b> Normal</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="join-distributions.html"><a href="join-distributions.html"><i class="fa fa-check"></i><b>1.4</b> Join Distributions</a></li>
<li class="chapter" data-level="1.5" data-path="likelihood.html"><a href="likelihood.html"><i class="fa fa-check"></i><b>1.5</b> Likelihood</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="discrete-analysis.html"><a href="discrete-analysis.html"><i class="fa fa-check"></i><b>2</b> Categorical Analysis - Nonmodel</a><ul>
<li class="chapter" data-level="2.1" data-path="chi-square-test.html"><a href="chi-square-test.html"><i class="fa fa-check"></i><b>2.1</b> Chi-Square Test</a></li>
<li class="chapter" data-level="2.2" data-path="one-way-tables.html"><a href="one-way-tables.html"><i class="fa fa-check"></i><b>2.2</b> One-Way Tables</a><ul>
<li class="chapter" data-level="2.2.1" data-path="one-way-tables.html"><a href="one-way-tables.html#chi-square-goodness-of-fit-test"><i class="fa fa-check"></i><b>2.2.1</b> Chi-Square Goodness-of-Fit Test</a></li>
<li class="chapter" data-level="2.2.2" data-path="one-way-tables.html"><a href="one-way-tables.html#proportion-test"><i class="fa fa-check"></i><b>2.2.2</b> Proportion Test</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="two-way-tables.html"><a href="two-way-tables.html"><i class="fa fa-check"></i><b>2.3</b> Two-Way Tables</a><ul>
<li class="chapter" data-level="2.3.1" data-path="two-way-tables.html"><a href="two-way-tables.html#chi-square-independence-test"><i class="fa fa-check"></i><b>2.3.1</b> Chi-Square Independence Test</a></li>
<li class="chapter" data-level="2.3.2" data-path="two-way-tables.html"><a href="two-way-tables.html#residuals-analysis"><i class="fa fa-check"></i><b>2.3.2</b> Residuals Analysis</a></li>
<li class="chapter" data-level="2.3.3" data-path="two-way-tables.html"><a href="two-way-tables.html#difference-in-proportions"><i class="fa fa-check"></i><b>2.3.3</b> Difference in Proportions</a></li>
<li class="chapter" data-level="2.3.4" data-path="two-way-tables.html"><a href="two-way-tables.html#relative-risk"><i class="fa fa-check"></i><b>2.3.4</b> Relative Risk</a></li>
<li class="chapter" data-level="2.3.5" data-path="two-way-tables.html"><a href="two-way-tables.html#odds-ratio"><i class="fa fa-check"></i><b>2.3.5</b> Odds Ratio</a></li>
<li class="chapter" data-level="2.3.6" data-path="two-way-tables.html"><a href="two-way-tables.html#partitioning-chi-square"><i class="fa fa-check"></i><b>2.3.6</b> Partitioning Chi-Square</a></li>
<li class="chapter" data-level="2.3.7" data-path="two-way-tables.html"><a href="two-way-tables.html#correlation"><i class="fa fa-check"></i><b>2.3.7</b> Correlation</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="k-way-tables.html"><a href="k-way-tables.html"><i class="fa fa-check"></i><b>2.4</b> K-Way Tables</a><ul>
<li class="chapter" data-level="2.4.1" data-path="k-way-tables.html"><a href="k-way-tables.html#odds-ratio-1"><i class="fa fa-check"></i><b>2.4.1</b> Odds Ratio</a></li>
<li class="chapter" data-level="2.4.2" data-path="k-way-tables.html"><a href="k-way-tables.html#chi-square-independence-test-1"><i class="fa fa-check"></i><b>2.4.2</b> Chi-Square Independence Test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="continuous-analysis.html"><a href="continuous-analysis.html"><i class="fa fa-check"></i><b>3</b> Continuous Variable Analysis</a><ul>
<li class="chapter" data-level="3.0.1" data-path="continuous-analysis.html"><a href="continuous-analysis.html#correlation-1"><i class="fa fa-check"></i><b>3.0.1</b> Correlation</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="experiment-design.html"><a href="experiment-design.html"><i class="fa fa-check"></i><b>4</b> Experiment Design</a><ul>
<li class="chapter" data-level="4.1" data-path="single-factor.html"><a href="single-factor.html"><i class="fa fa-check"></i><b>4.1</b> Single Factor</a></li>
<li class="chapter" data-level="4.2" data-path="blocking.html"><a href="blocking.html"><i class="fa fa-check"></i><b>4.2</b> Blocking</a></li>
<li class="chapter" data-level="4.3" data-path="nested.html"><a href="nested.html"><i class="fa fa-check"></i><b>4.3</b> Nested</a></li>
<li class="chapter" data-level="4.4" data-path="split-plot.html"><a href="split-plot.html"><i class="fa fa-check"></i><b>4.4</b> Split Plot</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-2-supervised-machine-learning.html"><a href="part-2-supervised-machine-learning.html"><i class="fa fa-check"></i>PART 2: Supervised Machine Learning</a></li>
<li class="chapter" data-level="5" data-path="ordinary-least-squares.html"><a href="ordinary-least-squares.html"><i class="fa fa-check"></i><b>5</b> Ordinary Least Squares</a><ul>
<li class="chapter" data-level="5.1" data-path="linear-regression-model.html"><a href="linear-regression-model.html"><i class="fa fa-check"></i><b>5.1</b> Linear Regression Model</a></li>
<li class="chapter" data-level="5.2" data-path="parameter-estimation.html"><a href="parameter-estimation.html"><i class="fa fa-check"></i><b>5.2</b> Parameter Estimation</a></li>
<li class="chapter" data-level="5.3" data-path="model-assumptions.html"><a href="model-assumptions.html"><i class="fa fa-check"></i><b>5.3</b> Model Assumptions</a><ul>
<li class="chapter" data-level="5.3.1" data-path="model-assumptions.html"><a href="model-assumptions.html#linearity"><i class="fa fa-check"></i><b>5.3.1</b> Linearity</a></li>
<li class="chapter" data-level="5.3.2" data-path="model-assumptions.html"><a href="model-assumptions.html#multicollinearity"><i class="fa fa-check"></i><b>5.3.2</b> Multicollinearity</a></li>
<li class="chapter" data-level="5.3.3" data-path="model-assumptions.html"><a href="model-assumptions.html#normality"><i class="fa fa-check"></i><b>5.3.3</b> Normality</a></li>
<li class="chapter" data-level="5.3.4" data-path="model-assumptions.html"><a href="model-assumptions.html#equal-variances"><i class="fa fa-check"></i><b>5.3.4</b> Equal Variances</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="prediction.html"><a href="prediction.html"><i class="fa fa-check"></i><b>5.4</b> Prediction</a></li>
<li class="chapter" data-level="5.5" data-path="inference.html"><a href="inference.html"><i class="fa fa-check"></i><b>5.5</b> Inference</a><ul>
<li class="chapter" data-level="5.5.1" data-path="inference.html"><a href="inference.html#t-test"><i class="fa fa-check"></i><b>5.5.1</b> <em>t</em>-Test</a></li>
<li class="chapter" data-level="5.5.2" data-path="inference.html"><a href="inference.html#f-test"><i class="fa fa-check"></i><b>5.5.2</b> <em>F</em>-Test</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="interpretation.html"><a href="interpretation.html"><i class="fa fa-check"></i><b>5.6</b> Interpretation</a></li>
<li class="chapter" data-level="5.7" data-path="model-validation.html"><a href="model-validation.html"><i class="fa fa-check"></i><b>5.7</b> Model Validation</a><ul>
<li class="chapter" data-level="5.7.1" data-path="model-validation.html"><a href="model-validation.html#accuracy-metrics"><i class="fa fa-check"></i><b>5.7.1</b> Accuracy Metrics</a></li>
<li class="chapter" data-level="5.7.2" data-path="model-validation.html"><a href="model-validation.html#cross-validation"><i class="fa fa-check"></i><b>5.7.2</b> Cross-Validation</a></li>
<li class="chapter" data-level="5.7.3" data-path="model-validation.html"><a href="model-validation.html#gain-curve"><i class="fa fa-check"></i><b>5.7.3</b> Gain Curve</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="reference.html"><a href="reference.html"><i class="fa fa-check"></i><b>5.8</b> Reference</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html"><i class="fa fa-check"></i><b>6</b> Generalized Linear Models</a><ul>
<li class="chapter" data-level="6.1" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>6.1</b> Logistic Regression</a></li>
<li class="chapter" data-level="6.2" data-path="multinomial-logistic-regression.html"><a href="multinomial-logistic-regression.html"><i class="fa fa-check"></i><b>6.2</b> Multinomial Logistic Regression</a></li>
<li class="chapter" data-level="6.3" data-path="ordinal-logistic-regression.html"><a href="ordinal-logistic-regression.html"><i class="fa fa-check"></i><b>6.3</b> Ordinal Logistic Regression</a><ul>
<li class="chapter" data-level="6.3.1" data-path="ordinal-logistic-regression.html"><a href="ordinal-logistic-regression.html#assumptions"><i class="fa fa-check"></i><b>6.3.1</b> Assumptions</a></li>
<li class="chapter" data-level="6.3.2" data-path="ordinal-logistic-regression.html"><a href="ordinal-logistic-regression.html#modeling"><i class="fa fa-check"></i><b>6.3.2</b> Modeling</a></li>
<li class="chapter" data-level="6.3.3" data-path="ordinal-logistic-regression.html"><a href="ordinal-logistic-regression.html#case-study"><i class="fa fa-check"></i><b>6.3.3</b> Case Study</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="poisson-regression.html"><a href="poisson-regression.html"><i class="fa fa-check"></i><b>6.4</b> Poisson Regression</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="multivariate-statistical-analysis.html"><a href="multivariate-statistical-analysis.html"><i class="fa fa-check"></i><b>7</b> Multivariate Statistical Analysis</a><ul>
<li class="chapter" data-level="7.1" data-path="background.html"><a href="background.html"><i class="fa fa-check"></i><b>7.1</b> Background</a></li>
<li class="chapter" data-level="7.2" data-path="manova.html"><a href="manova.html"><i class="fa fa-check"></i><b>7.2</b> MANOVA</a></li>
<li class="chapter" data-level="7.3" data-path="repeated-measures.html"><a href="repeated-measures.html"><i class="fa fa-check"></i><b>7.3</b> Repeated Measures</a></li>
<li class="chapter" data-level="7.4" data-path="lda.html"><a href="lda.html"><i class="fa fa-check"></i><b>7.4</b> LDA</a></li>
<li class="chapter" data-level="7.5" data-path="pca.html"><a href="pca.html"><i class="fa fa-check"></i><b>7.5</b> PCA</a></li>
<li class="chapter" data-level="7.6" data-path="factor-analysis.html"><a href="factor-analysis.html"><i class="fa fa-check"></i><b>7.6</b> Factor Analysis</a></li>
<li class="chapter" data-level="7.7" data-path="canonical-correlation.html"><a href="canonical-correlation.html"><i class="fa fa-check"></i><b>7.7</b> Canonical Correlation</a></li>
<li class="chapter" data-level="7.8" data-path="cluster-analysis.html"><a href="cluster-analysis.html"><i class="fa fa-check"></i><b>7.8</b> Cluster Analysis</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="classification.html"><a href="classification.html"><i class="fa fa-check"></i><b>8</b> Classification</a></li>
<li class="chapter" data-level="9" data-path="regularization.html"><a href="regularization.html"><i class="fa fa-check"></i><b>9</b> Regularization</a></li>
<li class="chapter" data-level="10" data-path="decision-trees.html"><a href="decision-trees.html"><i class="fa fa-check"></i><b>10</b> Decision Trees</a><ul>
<li class="chapter" data-level="10.1" data-path="classification-tree.html"><a href="classification-tree.html"><i class="fa fa-check"></i><b>10.1</b> Classification Tree</a><ul>
<li class="chapter" data-level="10.1.1" data-path="classification-tree.html"><a href="classification-tree.html#confusion-matrix"><i class="fa fa-check"></i><b>10.1.1</b> Confusion Matrix</a></li>
<li class="chapter" data-level="10.1.2" data-path="classification-tree.html"><a href="classification-tree.html#roc-curve"><i class="fa fa-check"></i><b>10.1.2</b> ROC Curve</a></li>
<li class="chapter" data-level="10.1.3" data-path="classification-tree.html"><a href="classification-tree.html#caret-approach"><i class="fa fa-check"></i><b>10.1.3</b> Caret Approach</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="regression-trees.html"><a href="regression-trees.html"><i class="fa fa-check"></i><b>10.2</b> Regression Trees</a><ul>
<li class="chapter" data-level="10.2.1" data-path="regression-trees.html"><a href="regression-trees.html#caret-approach-1"><i class="fa fa-check"></i><b>10.2.1</b> Caret Approach</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="bagging.html"><a href="bagging.html"><i class="fa fa-check"></i><b>10.3</b> Bagging</a></li>
<li class="chapter" data-level="10.4" data-path="random-forests.html"><a href="random-forests.html"><i class="fa fa-check"></i><b>10.4</b> Random Forests</a></li>
<li class="chapter" data-level="10.5" data-path="gradient-boosting.html"><a href="gradient-boosting.html"><i class="fa fa-check"></i><b>10.5</b> Gradient Boosting</a></li>
<li class="chapter" data-level="10.6" data-path="summary.html"><a href="summary.html"><i class="fa fa-check"></i><b>10.6</b> Summary</a></li>
<li class="chapter" data-level="10.7" data-path="reference-1.html"><a href="reference-1.html"><i class="fa fa-check"></i><b>10.7</b> Reference</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="non-linear-models.html"><a href="non-linear-models.html"><i class="fa fa-check"></i><b>11</b> Non-linear Models</a><ul>
<li class="chapter" data-level="11.1" data-path="splines.html"><a href="splines.html"><i class="fa fa-check"></i><b>11.1</b> Splines</a></li>
<li class="chapter" data-level="11.2" data-path="mars.html"><a href="mars.html"><i class="fa fa-check"></i><b>11.2</b> MARS</a></li>
<li class="chapter" data-level="11.3" data-path="gam.html"><a href="gam.html"><i class="fa fa-check"></i><b>11.3</b> GAM</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="support-vector-machines.html"><a href="support-vector-machines.html"><i class="fa fa-check"></i><b>12</b> Support Vector Machines</a><ul>
<li class="chapter" data-level="12.1" data-path="maximal-margin-classifier.html"><a href="maximal-margin-classifier.html"><i class="fa fa-check"></i><b>12.1</b> Maximal Margin Classifier</a></li>
<li class="chapter" data-level="12.2" data-path="support-vector-classifier.html"><a href="support-vector-classifier.html"><i class="fa fa-check"></i><b>12.2</b> Support Vector Classifier</a></li>
<li class="chapter" data-level="12.3" data-path="support-vector-machines-1.html"><a href="support-vector-machines-1.html"><i class="fa fa-check"></i><b>12.3</b> Support Vector Machines</a></li>
<li class="chapter" data-level="12.4" data-path="example-16.html"><a href="example-16.html"><i class="fa fa-check"></i><b>12.4</b> Example</a></li>
<li class="chapter" data-level="12.5" data-path="using-caret.html"><a href="using-caret.html"><i class="fa fa-check"></i><b>12.5</b> Using Caret</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="principal-components-analysis.html"><a href="principal-components-analysis.html"><i class="fa fa-check"></i><b>13</b> Principal Components Analysis</a></li>
<li class="chapter" data-level="14" data-path="text-mining.html"><a href="text-mining.html"><i class="fa fa-check"></i><b>14</b> Text Mining</a></li>
<li class="chapter" data-level="15" data-path="survival-analysis.html"><a href="survival-analysis.html"><i class="fa fa-check"></i><b>15</b> Survival Analysis</a><ul>
<li class="chapter" data-level="15.1" data-path="basic-concepts.html"><a href="basic-concepts.html"><i class="fa fa-check"></i><b>15.1</b> Basic Concepts</a></li>
<li class="chapter" data-level="15.2" data-path="survival-curve-estimation.html"><a href="survival-curve-estimation.html"><i class="fa fa-check"></i><b>15.2</b> Survival Curve Estimation</a><ul>
<li class="chapter" data-level="15.2.1" data-path="survival-curve-estimation.html"><a href="survival-curve-estimation.html#kaplan-meier"><i class="fa fa-check"></i><b>15.2.1</b> Kaplan-Meier</a></li>
<li class="chapter" data-level="15.2.2" data-path="survival-curve-estimation.html"><a href="survival-curve-estimation.html#weibull"><i class="fa fa-check"></i><b>15.2.2</b> Weibull</a></li>
<li class="chapter" data-level="15.2.3" data-path="survival-curve-estimation.html"><a href="survival-curve-estimation.html#cox"><i class="fa fa-check"></i><b>15.2.3</b> Cox</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html"><i class="fa fa-check"></i>Appendix</a><ul>
<li class="chapter" data-level="" data-path="publishing-to-bookdown.html"><a href="publishing-to-bookdown.html"><i class="fa fa-check"></i>Publishing to BookDown</a></li>
<li class="chapter" data-level="" data-path="shiny-apps.html"><a href="shiny-apps.html"><i class="fa fa-check"></i>Shiny Apps</a></li>
<li class="chapter" data-level="" data-path="packages.html"><a href="packages.html"><i class="fa fa-check"></i>Packages</a><ul>
<li class="chapter" data-level="" data-path="packages.html"><a href="packages.html#create-a-package"><i class="fa fa-check"></i>Create a package</a></li>
<li class="chapter" data-level="15.2.4" data-path="packages.html"><a href="packages.html#document-functions-with-roxygen"><i class="fa fa-check"></i><b>15.2.4</b> Document Functions with roxygen</a></li>
<li class="chapter" data-level="" data-path="packages.html"><a href="packages.html#create-data"><i class="fa fa-check"></i>Create Data</a></li>
<li class="chapter" data-level="" data-path="packages.html"><a href="packages.html#create-vignette"><i class="fa fa-check"></i>Create Vignette</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">My Data Science Notes</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="survival-curve-estimation" class="section level2">
<h2><span class="header-section-number">15.2</span> Survival Curve Estimation</h2>
<p>There are parametric and non-parametric methods to estimate a survivor curve. The usual non-parametric method is the <em>Kaplan-Meier</em> (KM) estimator. The usual parametric method is the <em>Weibull</em> distribution, of which the exponential distribution is a special case. In between the two is the <em>Cox proportional hazards model</em>, the most common way to estimate a survivor curve.</p>
<div id="kaplan-meier" class="section level3">
<h3><span class="header-section-number">15.2.1</span> Kaplan-Meier</h3>
<p>The Kaplan-Meier estimator for the survival function is</p>
<p><span class="math display">\[\hat{S} = \prod_{i: t_i &lt; t}{\frac{n_i - d_i}{n_i}}\]</span></p>
<p>where <span class="math inline">\(n_i\)</span> is the number of persons under observation at time <span class="math inline">\(i\)</span> and <span class="math inline">\(d_i\)</span> is the number of individuals dying at time <span class="math inline">\(i\)</span>. The Kaplan-Meier curve falls only when a subject dies, not when a subject is censored. Confidence limits can be calculated using the “delta” method to obtain the variance of <span class="math inline">\(\log \left(\hat{S}(t) \right)\)</span> (see p27 of Moore).</p>
<p>Calculate the Kaplan-Meier survival function estimate with the <code>survfit()</code> function. Here is an example using the <code>lung</code> data from the <code>survival</code> package to death of 228 patients witha advanced lung cancer. Column <code>status</code> indicates whether or not a person in the study has died (1 = censored, 2 = dead).</p>
<div class="sourceCode" id="cb746"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb746-1"><a href="survival-curve-estimation.html#cb746-1"></a><span class="kw">data</span>(lung, <span class="dt">package =</span> <span class="st">&quot;survival&quot;</span>)</span>
<span id="cb746-2"><a href="survival-curve-estimation.html#cb746-2"></a><span class="kw">head</span>(lung)</span></code></pre></div>
<pre><code>##   inst time status age sex ph.ecog ph.karno pat.karno meal.cal wt.loss
## 1    3  306      2  74   1       1       90       100     1175      NA
## 2    3  455      2  68   1       0       90        90     1225      15
## 3    3 1010      1  56   1       0       90        90       NA      15
## 4    5  210      2  57   1       1       90        60     1150      11
## 5    1  883      2  60   1       0      100        90       NA       0
## 6   12 1022      1  74   1       1       50        80      513       0</code></pre>
<p><code>survfit()</code> creates survival curves from a formula or from a previously fitted Cox model. The formula below is an intercept-only model. Structure the response variable as a <code>Surv</code> object.</p>
<div class="sourceCode" id="cb748"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb748-1"><a href="survival-curve-estimation.html#cb748-1"></a>km_fit &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(time, status) <span class="op">~</span><span class="st"> </span>sex, <span class="dt">data =</span> lung)</span>
<span id="cb748-2"><a href="survival-curve-estimation.html#cb748-2"></a>km_fit</span></code></pre></div>
<pre><code>## Call: survfit(formula = Surv(time, status) ~ sex, data = lung)
## 
##         n events median 0.95LCL 0.95UCL
## sex=1 138    112    270     212     310
## sex=2  90     53    426     348     550</code></pre>
<p>The printed <code>survfit</code> object shows there were 138 records (patients) for males (<code>sex=1</code>) and 90 records for females (<code>sex=2</code>), and 112 events (deaths) for males and 53 events for females. It also shows the 95% CI in days for the median time to event.</p>
<p>The <code>survfit</code> object contains more variables, including detailed <code>time</code> points with the number at risk <code>n.risk</code>, events <code>n.event</code>, and censors <code>n.censor</code> at each time point and strata <code>strata</code>.</p>
<div class="sourceCode" id="cb750"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb750-1"><a href="survival-curve-estimation.html#cb750-1"></a><span class="kw">data.frame</span>(</span>
<span id="cb750-2"><a href="survival-curve-estimation.html#cb750-2"></a>  <span class="dt">strata =</span> km_fit<span class="op">$</span>strata,</span>
<span id="cb750-3"><a href="survival-curve-estimation.html#cb750-3"></a>  <span class="dt">time =</span> km_fit<span class="op">$</span>time,</span>
<span id="cb750-4"><a href="survival-curve-estimation.html#cb750-4"></a>  <span class="dt">n.risk =</span> km_fit<span class="op">$</span>n.risk,</span>
<span id="cb750-5"><a href="survival-curve-estimation.html#cb750-5"></a>  <span class="dt">n.event =</span> km_fit<span class="op">$</span>n.event,</span>
<span id="cb750-6"><a href="survival-curve-estimation.html#cb750-6"></a>  <span class="dt">n.censor =</span> km_fit<span class="op">$</span>n.censor,</span>
<span id="cb750-7"><a href="survival-curve-estimation.html#cb750-7"></a>  <span class="dt">surv =</span> km_fit<span class="op">$</span>surv,</span>
<span id="cb750-8"><a href="survival-curve-estimation.html#cb750-8"></a>  <span class="dt">upper =</span> km_fit<span class="op">$</span>upper,</span>
<span id="cb750-9"><a href="survival-curve-estimation.html#cb750-9"></a>  <span class="dt">lower =</span> km_fit<span class="op">$</span>lower</span>
<span id="cb750-10"><a href="survival-curve-estimation.html#cb750-10"></a>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">head</span>()</span></code></pre></div>
<pre><code>##   strata time n.risk n.event n.censor surv upper lower
## 1    119   11    138       3        0 0.98  1.00  0.95
## 2     87   12    135       1        0 0.97  1.00  0.94
## 3    119   13    134       2        0 0.96  0.99  0.92
## 4     87   15    132       1        0 0.95  0.99  0.91
## 5    119   26    131       1        0 0.94  0.98  0.90
## 6     87   30    130       1        0 0.93  0.98  0.89</code></pre>
<p>Plot the fitted model with <code>ggsurvplot()</code>. A vertical drop in the curves indicates an event. The vertical tick mark on the curves means that a patient was censored.</p>
<div class="sourceCode" id="cb752"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb752-1"><a href="survival-curve-estimation.html#cb752-1"></a><span class="kw">ggsurvplot</span>(</span>
<span id="cb752-2"><a href="survival-curve-estimation.html#cb752-2"></a>  km_fit,</span>
<span id="cb752-3"><a href="survival-curve-estimation.html#cb752-3"></a>  <span class="dt">linetype =</span> <span class="st">&quot;strata&quot;</span>, <span class="co"># Change line type by groups</span></span>
<span id="cb752-4"><a href="survival-curve-estimation.html#cb752-4"></a>  <span class="dt">pval =</span> <span class="ot">TRUE</span>,</span>
<span id="cb752-5"><a href="survival-curve-estimation.html#cb752-5"></a>  <span class="dt">conf.int =</span> <span class="ot">TRUE</span>,</span>
<span id="cb752-6"><a href="survival-curve-estimation.html#cb752-6"></a>  <span class="dt">risk.table =</span> <span class="ot">TRUE</span>,</span>
<span id="cb752-7"><a href="survival-curve-estimation.html#cb752-7"></a>  <span class="dt">surv.median.line =</span> <span class="st">&quot;hv&quot;</span>, <span class="co"># median horizontal and vertical ref lines</span></span>
<span id="cb752-8"><a href="survival-curve-estimation.html#cb752-8"></a>  <span class="dt">ggtheme =</span> <span class="kw">theme_bw</span>(),</span>
<span id="cb752-9"><a href="survival-curve-estimation.html#cb752-9"></a>  <span class="dt">palette =</span> <span class="kw">c</span>(<span class="st">&quot;#E7B800&quot;</span>, <span class="st">&quot;#2E9FDF&quot;</span>),</span>
<span id="cb752-10"><a href="survival-curve-estimation.html#cb752-10"></a>  <span class="dt">title =</span> <span class="st">&quot;Kaplan-Meier Survival Function Estimate&quot;</span></span>
<span id="cb752-11"><a href="survival-curve-estimation.html#cb752-11"></a>)</span></code></pre></div>
<p><img src="data-sci_files/figure-html/unnamed-chunk-348-1.png" width="576" /></p>
<p>Reading the figure, you can see the median survival is 270 days for <code>sex=1</code> and 426 days for <code>sex=2</code>. These key values are available from the <code>summary()</code> object.</p>
<div class="sourceCode" id="cb753"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb753-1"><a href="survival-curve-estimation.html#cb753-1"></a><span class="kw">summary</span>(km_fit)<span class="op">$</span>table</span></code></pre></div>
<pre><code>##       records n.max n.start events *rmean *se(rmean) median 0.95LCL 0.95UCL
## sex=1     138   138     138    112    325         23    270     212     310
## sex=2      90    90      90     53    458         34    426     348     550</code></pre>
<p><code>ggsurvplot()</code> can plot the cumulative risk function (aka “cumulative incidence” or “cumulative events”), <span class="math inline">\(F(t) = 1 - S(t)\)</span>, with argument <code>fun = "event"</code>, and the cumulative hazard function, <span class="math inline">\(H(t) = -\log(S(t)).\)</span>, with argument <code>fun = "cumhaz"</code>.</p>
<div class="sourceCode" id="cb755"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb755-1"><a href="survival-curve-estimation.html#cb755-1"></a><span class="kw">ggsurvplot</span>(</span>
<span id="cb755-2"><a href="survival-curve-estimation.html#cb755-2"></a>  km_fit,</span>
<span id="cb755-3"><a href="survival-curve-estimation.html#cb755-3"></a>  <span class="dt">fun =</span> <span class="st">&quot;event&quot;</span>,</span>
<span id="cb755-4"><a href="survival-curve-estimation.html#cb755-4"></a>  <span class="dt">linetype =</span> <span class="st">&quot;strata&quot;</span>, <span class="co"># Change line type by groups</span></span>
<span id="cb755-5"><a href="survival-curve-estimation.html#cb755-5"></a>  <span class="dt">pval =</span> <span class="ot">TRUE</span>,</span>
<span id="cb755-6"><a href="survival-curve-estimation.html#cb755-6"></a>  <span class="dt">conf.int =</span> <span class="ot">TRUE</span>,</span>
<span id="cb755-7"><a href="survival-curve-estimation.html#cb755-7"></a>  <span class="dt">ggtheme =</span> <span class="kw">theme_bw</span>(),</span>
<span id="cb755-8"><a href="survival-curve-estimation.html#cb755-8"></a>  <span class="dt">palette =</span> <span class="kw">c</span>(<span class="st">&quot;#E7B800&quot;</span>, <span class="st">&quot;#2E9FDF&quot;</span>),</span>
<span id="cb755-9"><a href="survival-curve-estimation.html#cb755-9"></a>  <span class="dt">title =</span> <span class="st">&quot;Kaplan-Meier Cumulative Risk Function Estimate&quot;</span></span>
<span id="cb755-10"><a href="survival-curve-estimation.html#cb755-10"></a>)</span></code></pre></div>
<p><img src="data-sci_files/figure-html/unnamed-chunk-350-1.png" width="672" /></p>
<div class="sourceCode" id="cb756"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb756-1"><a href="survival-curve-estimation.html#cb756-1"></a><span class="kw">ggsurvplot</span>(</span>
<span id="cb756-2"><a href="survival-curve-estimation.html#cb756-2"></a>  km_fit,</span>
<span id="cb756-3"><a href="survival-curve-estimation.html#cb756-3"></a>  <span class="dt">fun =</span> <span class="st">&quot;cumhaz&quot;</span>,</span>
<span id="cb756-4"><a href="survival-curve-estimation.html#cb756-4"></a>  <span class="dt">linetype =</span> <span class="st">&quot;strata&quot;</span>, <span class="co"># Change line type by groups</span></span>
<span id="cb756-5"><a href="survival-curve-estimation.html#cb756-5"></a>  <span class="dt">pval =</span> <span class="ot">TRUE</span>,</span>
<span id="cb756-6"><a href="survival-curve-estimation.html#cb756-6"></a>  <span class="dt">conf.int =</span> <span class="ot">TRUE</span>,</span>
<span id="cb756-7"><a href="survival-curve-estimation.html#cb756-7"></a>  <span class="dt">ggtheme =</span> <span class="kw">theme_bw</span>(),</span>
<span id="cb756-8"><a href="survival-curve-estimation.html#cb756-8"></a>  <span class="dt">palette =</span> <span class="kw">c</span>(<span class="st">&quot;#E7B800&quot;</span>, <span class="st">&quot;#2E9FDF&quot;</span>),</span>
<span id="cb756-9"><a href="survival-curve-estimation.html#cb756-9"></a>  <span class="dt">title =</span> <span class="st">&quot;Kaplan-Meier Cumulative Hazard Function Estimate&quot;</span></span>
<span id="cb756-10"><a href="survival-curve-estimation.html#cb756-10"></a>)</span></code></pre></div>
<p><img src="data-sci_files/figure-html/unnamed-chunk-351-1.png" width="672" /></p>
<p><code>ggsurvplot()</code> can produce faceted plots for more complicated analyses. For example, fit a survival curve to the <code>survival::colon</code> data set with predictors <code>sex</code>, <code>rx</code>, and <code>adhere</code>.</p>
<div class="sourceCode" id="cb757"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb757-1"><a href="survival-curve-estimation.html#cb757-1"></a>km_fit_colon &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(time, status) <span class="op">~</span><span class="st"> </span>sex <span class="op">+</span><span class="st"> </span>rx <span class="op">+</span><span class="st"> </span>adhere, <span class="dt">data =</span> colon)</span>
<span id="cb757-2"><a href="survival-curve-estimation.html#cb757-2"></a></span>
<span id="cb757-3"><a href="survival-curve-estimation.html#cb757-3"></a>p &lt;-<span class="st"> </span>km_fit_colon <span class="op">%&gt;%</span></span>
<span id="cb757-4"><a href="survival-curve-estimation.html#cb757-4"></a><span class="st">  </span><span class="kw">ggsurvplot</span>(<span class="dt">fun =</span> <span class="st">&quot;event&quot;</span>, </span>
<span id="cb757-5"><a href="survival-curve-estimation.html#cb757-5"></a>             <span class="dt">conf.int =</span> <span class="ot">TRUE</span>,</span>
<span id="cb757-6"><a href="survival-curve-estimation.html#cb757-6"></a>             <span class="dt">ggtheme =</span> <span class="kw">theme_bw</span>()) </span>
<span id="cb757-7"><a href="survival-curve-estimation.html#cb757-7"></a>p<span class="op">$</span>plot <span class="op">+</span><span class="st"> </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">&quot;right&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">facet_grid</span>(rx <span class="op">~</span><span class="st"> </span>adhere)</span></code></pre></div>
<p><img src="data-sci_files/figure-html/unnamed-chunk-352-1.png" width="672" /></p>
<div id="log-rank-test" class="section level4">
<h4><span class="header-section-number">15.2.1.1</span> Log-Rank Test</h4>
<p>Compare survival curves with the log-rank test (<span class="math inline">\(H_0\)</span>: no difference). The log rank test is a non-parametric test, so it makes no assumptions about the survival distributions. The log rank test compares the observed and expected (<span class="math inline">\(H_0\)</span>) number of events in each group. The log rank test statistic is approximately chi-square distributed.</p>
<p>Function <code>survdiff()</code> performs the log-rank test.</p>
<div class="sourceCode" id="cb758"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb758-1"><a href="survival-curve-estimation.html#cb758-1"></a>km_diff &lt;-<span class="st"> </span><span class="kw">survdiff</span>(<span class="kw">Surv</span>(time, status) <span class="op">~</span><span class="st"> </span>sex, <span class="dt">data =</span> lung)</span>
<span id="cb758-2"><a href="survival-curve-estimation.html#cb758-2"></a>km_diff</span></code></pre></div>
<pre><code>## Call:
## survdiff(formula = Surv(time, status) ~ sex, data = lung)
## 
##         N Observed Expected (O-E)^2/E (O-E)^2/V
## sex=1 138      112     91.6      4.55      10.3
## sex=2  90       53     73.4      5.68      10.3
## 
##  Chisq= 10.3  on 1 degrees of freedom, p= 0.001</code></pre>
<p>The chi-sq test statistic is 10.3 on one d.f., for a p-value of 0.001, so yes, males and females had different survival patterns.</p>
</div>
</div>
<div id="weibull" class="section level3">
<h3><span class="header-section-number">15.2.2</span> Weibull</h3>
<p>Several parametric distributions are available for modeling survival data. The exponential distribution is the easiest to use because it has a constant hazard <span class="math inline">\(h(t) = \lambda\)</span>. The cumulative hazard is <span class="math inline">\(H(t) = \int_0^t \lambda dt = \lambda t\)</span> and the corresponding survival function is</p>
<p><span class="math display">\[S(t) = e^{-H(t)} = e^{-\lambda t}.\]</span></p>
<p>The expected survival time is <span class="math inline">\(E(T) = \int_0^\infty S(t)dt = \int_0^\infty d^{-\lambda t} dt = 1 / \lambda.\)</span>. The median survival time is <span class="math inline">\(S(t) = e^{-\lambda t} = 0.5\)</span>, or <span class="math inline">\(t_{med} = \log(2) / \lambda\)</span>.</p>
<p>The Weibull distribution is more appropriate for modeling lifetimes, however. The Weibull hazard function is <span class="math inline">\(h(t) = \alpha \lambda (\lambda t)^{\alpha - 1} = \alpha \lambda^\alpha t^{\alpha-1}\)</span>.</p>
<div class="sourceCode" id="cb760"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb760-1"><a href="survival-curve-estimation.html#cb760-1"></a><span class="kw">data.frame</span>(<span class="dt">t =</span> <span class="kw">rep</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">80</span>, <span class="dv">3</span>),</span>
<span id="cb760-2"><a href="survival-curve-estimation.html#cb760-2"></a>           <span class="dt">alpha =</span> <span class="kw">c</span>(<span class="kw">rep</span>(<span class="fl">1.5</span>, <span class="dv">80</span>), <span class="kw">rep</span>(<span class="dv">1</span>, <span class="dv">80</span>), <span class="kw">rep</span>(<span class="fl">0.75</span>, <span class="dv">80</span>)),</span>
<span id="cb760-3"><a href="survival-curve-estimation.html#cb760-3"></a>           <span class="dt">lambda =</span> <span class="kw">rep</span>(<span class="fl">0.03</span>, <span class="dv">240</span>)) <span class="op">%&gt;%</span></span>
<span id="cb760-4"><a href="survival-curve-estimation.html#cb760-4"></a><span class="st">  </span><span class="kw">mutate</span>(</span>
<span id="cb760-5"><a href="survival-curve-estimation.html#cb760-5"></a>    <span class="dt">f =</span> <span class="kw">dweibull</span>(<span class="dt">x =</span> t, <span class="dt">shape =</span> alpha, <span class="dt">scale =</span> <span class="dv">1</span> <span class="op">/</span><span class="st"> </span><span class="fl">0.03</span>),</span>
<span id="cb760-6"><a href="survival-curve-estimation.html#cb760-6"></a>    <span class="dt">S =</span> <span class="kw">pweibull</span>(<span class="dt">q =</span> t, <span class="dt">shape =</span> alpha, <span class="dt">scale =</span> <span class="dv">1</span> <span class="op">/</span><span class="st"> </span><span class="fl">0.03</span>, <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>),</span>
<span id="cb760-7"><a href="survival-curve-estimation.html#cb760-7"></a>    <span class="dt">h =</span> f <span class="op">/</span><span class="st"> </span>S  <span class="co"># same as alpha * lambda^alpha * t^(alpha-1)</span></span>
<span id="cb760-8"><a href="survival-curve-estimation.html#cb760-8"></a>  ) <span class="op">%&gt;%</span></span>
<span id="cb760-9"><a href="survival-curve-estimation.html#cb760-9"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> t, <span class="dt">y =</span> h, <span class="dt">color =</span> <span class="kw">as.factor</span>(alpha))) <span class="op">+</span></span>
<span id="cb760-10"><a href="survival-curve-estimation.html#cb760-10"></a><span class="st">  </span><span class="kw">geom_line</span>() <span class="op">+</span></span>
<span id="cb760-11"><a href="survival-curve-estimation.html#cb760-11"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">&quot;top&quot;</span>) <span class="op">+</span></span>
<span id="cb760-12"><a href="survival-curve-estimation.html#cb760-12"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">y =</span> <span class="st">&quot;hazard&quot;</span>, <span class="dt">x =</span> <span class="st">&quot;time&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;alpha&quot;</span>,</span>
<span id="cb760-13"><a href="survival-curve-estimation.html#cb760-13"></a>       <span class="dt">title =</span> <span class="st">&quot;Weibul hazard function at varying levels of alpha&quot;</span>,</span>
<span id="cb760-14"><a href="survival-curve-estimation.html#cb760-14"></a>       <span class="dt">subtitle =</span> <span class="st">&quot;Lambda = 0.03&quot;</span>,</span>
<span id="cb760-15"><a href="survival-curve-estimation.html#cb760-15"></a>       <span class="dt">caption =</span> <span class="st">&quot;alpha = 1 is special case of exponential function.&quot;</span>)</span></code></pre></div>
<p><img src="data-sci_files/figure-html/unnamed-chunk-354-1.png" width="672" /></p>
<p>The cumulative hazard function is <span class="math inline">\(H(t) = (\lambda t)^\alpha\)</span> and the corresponding survival function is</p>
<p><span class="math display">\[S(t) = e^{-(\lambda t)^\alpha}.\]</span></p>
<p>The exponential distribution is a special case of the Weibull where <span class="math inline">\(\alpha = 1\)</span>. The expected survival time is <span class="math inline">\(E(t) = \frac{\Gamma (1 + 1 / \alpha)}{\lambda}\)</span>. The median survival time is <span class="math inline">\(t_{med} = \frac{[\log(2)]^{1 / \alpha}}{\lambda}\)</span></p>
<p>The Kaplan-Meier estimate is used mainly as a descriptive tool. The Weibull model produces a smooth survival curve instead of a step function. The Weibull model assumes a Weibull distribution.</p>
<p>Fit a Weibull model with the <code>survreg()</code> function.</p>
<div class="sourceCode" id="cb761"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb761-1"><a href="survival-curve-estimation.html#cb761-1"></a><span class="kw">data</span>(GBSG2, <span class="dt">package =</span> <span class="st">&quot;TH.data&quot;</span>)</span>
<span id="cb761-2"><a href="survival-curve-estimation.html#cb761-2"></a>wb &lt;-<span class="st"> </span><span class="kw">survreg</span>(<span class="kw">Surv</span>(time, cens) <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> GBSG2)</span>
<span id="cb761-3"><a href="survival-curve-estimation.html#cb761-3"></a></span>
<span id="cb761-4"><a href="survival-curve-estimation.html#cb761-4"></a><span class="co"># 90% of patients survive beyond time point 385</span></span>
<span id="cb761-5"><a href="survival-curve-estimation.html#cb761-5"></a><span class="co"># Alternatively, 10% of patients die at time 385</span></span>
<span id="cb761-6"><a href="survival-curve-estimation.html#cb761-6"></a><span class="kw">predict</span>(wb, <span class="dt">type =</span> <span class="st">&quot;quantile&quot;</span>, <span class="dt">p =</span> <span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="fl">0.9</span>, <span class="dt">newdata =</span> <span class="kw">data.frame</span>(<span class="dv">1</span>))</span></code></pre></div>
<pre><code>##   1 
## 385</code></pre>
<div class="sourceCode" id="cb763"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb763-1"><a href="survival-curve-estimation.html#cb763-1"></a><span class="co"># The median survival time is 1694</span></span>
<span id="cb763-2"><a href="survival-curve-estimation.html#cb763-2"></a><span class="kw">predict</span>(wb, <span class="dt">type =</span> <span class="st">&quot;quantile&quot;</span>, <span class="dt">p =</span> <span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="fl">0.5</span>, <span class="dt">newdata =</span> <span class="kw">data.frame</span>(<span class="dv">1</span>))</span></code></pre></div>
<pre><code>##    1 
## 1694</code></pre>
<div class="sourceCode" id="cb765"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb765-1"><a href="survival-curve-estimation.html#cb765-1"></a>surv &lt;-<span class="st"> </span><span class="kw">seq</span>(.<span class="dv">99</span>, <span class="fl">.01</span>, <span class="dt">by =</span> <span class="fl">-.01</span>)</span>
<span id="cb765-2"><a href="survival-curve-estimation.html#cb765-2"></a>t &lt;-<span class="st"> </span><span class="kw">predict</span>(wb, <span class="dt">type =</span> <span class="st">&quot;quantile&quot;</span>, <span class="dt">p =</span> <span class="dv">1</span> <span class="op">-</span><span class="st"> </span>surv, <span class="dt">newdata =</span> <span class="kw">data.frame</span>(<span class="dv">1</span>))</span>
<span id="cb765-3"><a href="survival-curve-estimation.html#cb765-3"></a><span class="kw">head</span>(<span class="kw">data.frame</span>(<span class="dt">time =</span> t, <span class="dt">surv =</span> surv))</span></code></pre></div>
<pre><code>##   time surv
## 1   61 0.99
## 2  105 0.98
## 3  145 0.97
## 4  183 0.96
## 5  219 0.95
## 6  253 0.94</code></pre>
<div class="sourceCode" id="cb767"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb767-1"><a href="survival-curve-estimation.html#cb767-1"></a>surv_wb &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">time =</span> t, <span class="dt">surv =</span> surv, </span>
<span id="cb767-2"><a href="survival-curve-estimation.html#cb767-2"></a>                      <span class="dt">upper =</span> <span class="ot">NA</span>, <span class="dt">lower =</span> <span class="ot">NA</span>, <span class="dt">std.err =</span> <span class="ot">NA</span>)</span>
<span id="cb767-3"><a href="survival-curve-estimation.html#cb767-3"></a><span class="kw">ggsurvplot_df</span>(<span class="dt">fit =</span> surv_wb, <span class="dt">surv.geom =</span> geom_line)</span></code></pre></div>
<p><img src="data-sci_files/figure-html/unnamed-chunk-355-1.png" width="672" /></p>
<p>Fit a Weibull model controlling for hormonal therapy <code>horTh</code> and tumor size <code>tsize</code>.</p>
<div class="sourceCode" id="cb768"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb768-1"><a href="survival-curve-estimation.html#cb768-1"></a>wbmod &lt;-<span class="st"> </span><span class="kw">survreg</span>(<span class="kw">Surv</span>(time, cens) <span class="op">~</span><span class="st"> </span>horTh <span class="op">+</span><span class="st"> </span>tsize, <span class="dt">data =</span> GBSG2)</span>
<span id="cb768-2"><a href="survival-curve-estimation.html#cb768-2"></a></span>
<span id="cb768-3"><a href="survival-curve-estimation.html#cb768-3"></a><span class="kw">coef</span>(wbmod)</span></code></pre></div>
<pre><code>## (Intercept)    horThyes       tsize 
##       7.961       0.312      -0.012</code></pre>
<div class="sourceCode" id="cb770"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb770-1"><a href="survival-curve-estimation.html#cb770-1"></a><span class="kw">summary</span>(wbmod)</span></code></pre></div>
<pre><code>## 
## Call:
## survreg(formula = Surv(time, cens) ~ horTh + tsize, data = GBSG2)
##                Value Std. Error     z                    p
## (Intercept)  7.96070    0.10413 76.45 &lt; 0.0000000000000002
## horThyes     0.31176    0.09602  3.25               0.0012
## tsize       -0.01218    0.00272 -4.47          0.000007772
## Log(scale)  -0.26494    0.04952 -5.35          0.000000088
## 
## Scale= 0.767 
## 
## Weibull distribution
## Loglik(model)= -2623   Loglik(intercept only)= -2637
##  Chisq= 28 on 2 degrees of freedom, p= 0.00000076 
## Number of Newton-Raphson Iterations: 5 
## n= 686</code></pre>
<div class="sourceCode" id="cb772"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb772-1"><a href="survival-curve-estimation.html#cb772-1"></a>surv &lt;-<span class="st"> </span><span class="kw">seq</span>(.<span class="dv">99</span>, <span class="fl">.01</span>, <span class="dt">by =</span> <span class="fl">-.01</span>)</span>
<span id="cb772-2"><a href="survival-curve-estimation.html#cb772-2"></a>newdata &lt;-<span class="st"> </span><span class="kw">expand.grid</span>(</span>
<span id="cb772-3"><a href="survival-curve-estimation.html#cb772-3"></a>    <span class="dt">horTh =</span> <span class="kw">levels</span>(GBSG2<span class="op">$</span>horTh),</span>
<span id="cb772-4"><a href="survival-curve-estimation.html#cb772-4"></a>    <span class="dt">tsize =</span> <span class="kw">quantile</span>(GBSG2<span class="op">$</span>tsize, <span class="dt">probs =</span> <span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.50</span>, <span class="fl">0.75</span>))</span>
<span id="cb772-5"><a href="survival-curve-estimation.html#cb772-5"></a>)</span>
<span id="cb772-6"><a href="survival-curve-estimation.html#cb772-6"></a>t &lt;-<span class="st"> </span><span class="kw">predict</span>(wbmod, <span class="dt">type =</span> <span class="st">&quot;quantile&quot;</span>, <span class="dt">p =</span> <span class="dv">1</span> <span class="op">-</span><span class="st"> </span>surv, <span class="dt">newdata =</span> newdata)</span>
<span id="cb772-7"><a href="survival-curve-estimation.html#cb772-7"></a></span>
<span id="cb772-8"><a href="survival-curve-estimation.html#cb772-8"></a>surv_wbmod &lt;-<span class="st"> </span>surv_wbmod_wide &lt;-<span class="st"> </span><span class="kw">cbind</span>(newdata, t) <span class="op">%&gt;%</span></span>
<span id="cb772-9"><a href="survival-curve-estimation.html#cb772-9"></a><span class="st">    </span><span class="kw">pivot_longer</span>(<span class="dt">names_to =</span> <span class="st">&quot;surv_id&quot;</span>, <span class="dt">values_to =</span> <span class="st">&quot;time&quot;</span>, <span class="dt">cols =</span> <span class="op">-</span><span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>)) <span class="op">%&gt;%</span></span>
<span id="cb772-10"><a href="survival-curve-estimation.html#cb772-10"></a><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">tsize =</span> <span class="kw">as.numeric</span>(tsize),</span>
<span id="cb772-11"><a href="survival-curve-estimation.html#cb772-11"></a>           <span class="dt">surv_id =</span> <span class="kw">as.factor</span>(<span class="kw">as.numeric</span>(surv_id))) <span class="op">%&gt;%</span></span>
<span id="cb772-12"><a href="survival-curve-estimation.html#cb772-12"></a><span class="st">    </span><span class="kw">data.frame</span>()</span>
<span id="cb772-13"><a href="survival-curve-estimation.html#cb772-13"></a>surv_wbmod<span class="op">$</span>surv =<span class="st"> </span>surv[<span class="kw">as.numeric</span>(surv_wbmod<span class="op">$</span>surv_id)]</span>
<span id="cb772-14"><a href="survival-curve-estimation.html#cb772-14"></a>surv_wbmod<span class="op">$</span>upper =<span class="st"> </span><span class="ot">NA</span></span>
<span id="cb772-15"><a href="survival-curve-estimation.html#cb772-15"></a>surv_wbmod<span class="op">$</span>lower =<span class="st"> </span><span class="ot">NA</span></span>
<span id="cb772-16"><a href="survival-curve-estimation.html#cb772-16"></a>surv_wbmod<span class="op">$</span>std.err =<span class="st"> </span><span class="ot">NA</span></span>
<span id="cb772-17"><a href="survival-curve-estimation.html#cb772-17"></a>surv_wbmod<span class="op">$</span>strata =<span class="st"> </span><span class="ot">NA</span></span>
<span id="cb772-18"><a href="survival-curve-estimation.html#cb772-18"></a>surv_wbmod[, <span class="kw">c</span>(<span class="st">&quot;upper&quot;</span>, <span class="st">&quot;lower&quot;</span>, <span class="st">&quot;std.err&quot;</span>, <span class="st">&quot;strata&quot;</span>)] &lt;-<span class="st"> </span><span class="ot">NA</span></span>
<span id="cb772-19"><a href="survival-curve-estimation.html#cb772-19"></a><span class="kw">ggsurvplot_df</span>(surv_wbmod, <span class="dt">surv.geom =</span> geom_line,</span>
<span id="cb772-20"><a href="survival-curve-estimation.html#cb772-20"></a>  <span class="dt">linetype =</span> <span class="st">&quot;horTh&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;tsize&quot;</span>, <span class="dt">legend.title =</span> <span class="ot">NULL</span>)</span></code></pre></div>
<p><img src="data-sci_files/figure-html/unnamed-chunk-356-1.png" width="672" /></p>
<p>Interpret the coefficient as the probability of surviving falls by 0.012 per unit increase in the tumor size and increases by 0.312 if taking hormonal therapy.</p>
<p>You can fit other models with the <code>dist = c("lognormal", "exponential")</code> parameter.</p>
</div>
<div id="cox" class="section level3">
<h3><span class="header-section-number">15.2.3</span> Cox</h3>
<p>The Cox proportional hazards model uses partial likelihood to fit a regression model to censored survival data, much like linear regression. Partial likelihood differs from a likelihood in two ways. First, it is a product of expressions, one for each failure time (censoring times do not contribute any factors). Second, the factors of a partial likelihood are conditional probabilities.</p>
<p>Kaplan-Meier curves and logrank tests are examples of univariate analysis. They describe the survival as a function of a single categorical factor variable. The Cox proportional hazards model describes the function of multiple covariates.</p>
<p>The hazard function for subject <span class="math inline">\(i\)</span> at time <span class="math inline">\(t\)</span> is <span class="math inline">\(h_i(t) = h_0(t) \psi_i\)</span> where <span class="math inline">\(\psi_i = e^{X_i \beta}\)</span> and <span class="math inline">\(X\)</span> is a set of coveriates. <span class="math inline">\(h_0(t)\)</span> is the baseline hazard, the value when all the <span class="math inline">\(X\)</span> covariates equal zero (<span class="math inline">\(e^{X_i \beta} = 1\)</span>). The Cox model can be written as a multiple linear regression of the logarithm of the hazard on the variables, with the baseline hazard intercept that varies with time. The <span class="math inline">\(e^{\beta_j}\)</span> values are called the hazard ratios. A positive <span class="math inline">\(e^{\beta_j}\)</span> means the hazard increases with the covariate.</p>
<p>The Cox model is a proportional-hazards model, meaning the hazard of the event in any group is a constant multiple of the hazard in any other.</p>
<p>Consider the first failure time, <span class="math inline">\(t_1\)</span>. The probability that patient <span class="math inline">\(i\)</span> is the one to fail is the proportion of patient <span class="math inline">\(i\)</span>’s hazard divided by the sum of the hazards of all <span class="math inline">\(R_1\)</span> patients at risk,</p>
<p><span class="math display">\[p_1 = \frac{h_i(t_1)}{\sum_{k \in R_1} h_k(t_1)} = \frac{h_0(t_1) \psi_i}{\sum_{k \in R_1} h_0(t_1) \psi_k} = \frac{\psi_i}{\sum_{k \in R_1} \psi_k}\]</span></p>
<p>The hazard ratio is time independent - the patient survivor curves are proportional to each other.</p>
<p>The next failure event has a reduced <span class="math inline">\(R_2\)</span> patients at risk. The partial likelihood for <span class="math inline">\(D\)</span> failure times is the product <span class="math inline">\(L_i = p_1 p_2 \cdots p_D\)</span>. The Cox model uses maximum partial likelihood estimation to find the value of <span class="math inline">\(\phi\)</span> that maximizes the likelihood function.</p>
<p>Fit a Cox proportional hazards model with <code>coxph()</code>. Here is a simple Cox proportional hazards model for a single covariate, <code>sex</code>.</p>
<div class="sourceCode" id="cb773"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb773-1"><a href="survival-curve-estimation.html#cb773-1"></a>lung_cox &lt;-<span class="st"> </span><span class="kw">coxph</span>(<span class="kw">Surv</span>(time, status) <span class="op">~</span><span class="st"> </span>sex, <span class="dt">data =</span> lung)</span>
<span id="cb773-2"><a href="survival-curve-estimation.html#cb773-2"></a><span class="kw">summary</span>(lung_cox)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(time, status) ~ sex, data = lung)
## 
##   n= 228, number of events= 165 
## 
##       coef exp(coef) se(coef)     z Pr(&gt;|z|)   
## sex -0.531     0.588    0.167 -3.18   0.0015 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##     exp(coef) exp(-coef) lower .95 upper .95
## sex     0.588        1.7     0.424     0.816
## 
## Concordance= 0.579  (se = 0.021 )
## Likelihood ratio test= 10.6  on 1 df,   p=0.001
## Wald test            = 10.1  on 1 df,   p=0.001
## Score (logrank) test = 10.3  on 1 df,   p=0.001</code></pre>
<p>The Wald statistic (z) is the ratio of each regression coefficient to its standard error (<code>z = coef/se(coef)</code>), just as with linear regression.</p>
<p>The negative coefficient estimator sign means that the hazard (risk of death) decreases with increasing values of the variable. <code>sex</code> is encoded as a 1 = male, 2 = female, so sex = -0.5310 means females have a lower risk of death than males.</p>
<p>The exponentiated coefficients (<code>exp(coef)</code>) are the hazard ratios, the effect-size of the covariates. Being female (sex=2) reduces the hazard by a factor of 0.5880 (41%).</p>
<p>Below the coefficients estimators table is a table of hazard ratio Confidence intervals.</p>
<p>The last section of the summary object is three tests for the overall significance of the model: the likelihood-ratio test, Wald test, and score logrank statistics. These three methods are asymptotically equivalent. The Likelihood ratio test has better behavior for small sample sizes, so it is generally preferred.</p>
<p>A multivariate analysis works the same way. Here is the Cox model with two additional covariates: <code>age</code> and <code>ph.ecog</code>.</p>
<div class="sourceCode" id="cb775"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb775-1"><a href="survival-curve-estimation.html#cb775-1"></a>lung_cox_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">coxph</span>(<span class="kw">Surv</span>(time, status) <span class="op">~</span><span class="st"> </span>age <span class="op">+</span><span class="st"> </span>sex <span class="op">+</span><span class="st"> </span>ph.ecog, <span class="dt">data =</span> lung)</span>
<span id="cb775-2"><a href="survival-curve-estimation.html#cb775-2"></a><span class="kw">summary</span>(lung_cox_<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(time, status) ~ age + sex + ph.ecog, data = lung)
## 
##   n= 227, number of events= 164 
##    (1 observation deleted due to missingness)
## 
##             coef exp(coef) se(coef)     z Pr(&gt;|z|)    
## age      0.01107   1.01113  0.00927  1.19  0.23242    
## sex     -0.55261   0.57544  0.16774 -3.29  0.00099 ***
## ph.ecog  0.46373   1.58999  0.11358  4.08 0.000044 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##         exp(coef) exp(-coef) lower .95 upper .95
## age         1.011      0.989     0.993     1.030
## sex         0.575      1.738     0.414     0.799
## ph.ecog     1.590      0.629     1.273     1.986
## 
## Concordance= 0.637  (se = 0.025 )
## Likelihood ratio test= 30.5  on 3 df,   p=0.000001
## Wald test            = 29.9  on 3 df,   p=0.000001
## Score (logrank) test = 30.5  on 3 df,   p=0.000001</code></pre>
<p>The p-values for all three overall tests (likelihood, Wald, and score) are significant, indicating that the model is significant (not all <span class="math inline">\(\beta\)</span> values are 0).</p>
<p>Having fit a Cox model to the data, it’s possible to visualize the predicted survival proportion at any given time for a particular risk group. Function <code>survfit()</code> estimates the survival proportion at the mean values of covariates by default.</p>
<div class="sourceCode" id="cb777"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb777-1"><a href="survival-curve-estimation.html#cb777-1"></a><span class="kw">ggsurvplot</span>(<span class="kw">surv_fit</span>(lung_cox_<span class="dv">2</span>, <span class="dt">data =</span> lung), </span>
<span id="cb777-2"><a href="survival-curve-estimation.html#cb777-2"></a>           <span class="dt">palette =</span> <span class="st">&quot;#2E9FDF&quot;</span>, <span class="dt">ggtheme =</span> <span class="kw">theme_minimal</span>())</span></code></pre></div>
<p><img src="data-sci_files/figure-html/unnamed-chunk-359-1.png" width="672" /></p>
<p>To display the effects of one or more particular covariates, construct a data frame with test cases and pass to <code>survfit()</code> with the <code>newdata</code> argument.</p>
<div class="sourceCode" id="cb778"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb778-1"><a href="survival-curve-estimation.html#cb778-1"></a>newdata &lt;-<span class="st"> </span><span class="kw">expand.grid</span>(</span>
<span id="cb778-2"><a href="survival-curve-estimation.html#cb778-2"></a>    <span class="dt">sex =</span> <span class="kw">unique</span>(lung<span class="op">$</span>sex),</span>
<span id="cb778-3"><a href="survival-curve-estimation.html#cb778-3"></a><span class="co">#    age = quantile(lung$age, probs = c(0.25, 0.50, 0.75)),</span></span>
<span id="cb778-4"><a href="survival-curve-estimation.html#cb778-4"></a>    <span class="dt">age =</span> <span class="kw">median</span>(lung<span class="op">$</span>age),</span>
<span id="cb778-5"><a href="survival-curve-estimation.html#cb778-5"></a>    <span class="dt">ph.ecog =</span> <span class="dv">1</span></span>
<span id="cb778-6"><a href="survival-curve-estimation.html#cb778-6"></a>)</span>
<span id="cb778-7"><a href="survival-curve-estimation.html#cb778-7"></a><span class="kw">rownames</span>(newdata) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;male&quot;</span>, <span class="st">&quot;female&quot;</span>)</span>
<span id="cb778-8"><a href="survival-curve-estimation.html#cb778-8"></a></span>
<span id="cb778-9"><a href="survival-curve-estimation.html#cb778-9"></a><span class="co"># Create survival curves.  The rownames show up in the model</span></span>
<span id="cb778-10"><a href="survival-curve-estimation.html#cb778-10"></a>lung_pred &lt;-<span class="st"> </span><span class="kw">survfit</span>(lung_cox_<span class="dv">2</span>, <span class="dt">newdata =</span> newdata, <span class="dt">data =</span> lung)</span>
<span id="cb778-11"><a href="survival-curve-estimation.html#cb778-11"></a></span>
<span id="cb778-12"><a href="survival-curve-estimation.html#cb778-12"></a><span class="co"># surv_summary() creates the data.frame with a summary of the survfit() results, including columns like time (survival time) and surv (survival probability).</span></span>
<span id="cb778-13"><a href="survival-curve-estimation.html#cb778-13"></a>lung_pred0 &lt;-<span class="st"> </span><span class="kw">surv_summary</span>(lung_pred)</span>
<span id="cb778-14"><a href="survival-curve-estimation.html#cb778-14"></a><span class="co"># get the corresponding new_data cols</span></span>
<span id="cb778-15"><a href="survival-curve-estimation.html#cb778-15"></a>lung_pred1 &lt;-<span class="st"> </span><span class="kw">cbind</span>(lung_pred0, newdata[<span class="kw">as.character</span>(lung_pred0<span class="op">$</span>strata), ])</span>
<span id="cb778-16"><a href="survival-curve-estimation.html#cb778-16"></a><span class="kw">ggsurvplot_df</span>(</span>
<span id="cb778-17"><a href="survival-curve-estimation.html#cb778-17"></a>  lung_pred1, </span>
<span id="cb778-18"><a href="survival-curve-estimation.html#cb778-18"></a>  <span class="dt">color =</span> <span class="st">&quot;sex&quot;</span>, </span>
<span id="cb778-19"><a href="survival-curve-estimation.html#cb778-19"></a>  <span class="dt">legend.labs =</span> <span class="kw">c</span>(<span class="st">&quot;M&quot;</span>, <span class="st">&quot;F&quot;</span>),</span>
<span id="cb778-20"><a href="survival-curve-estimation.html#cb778-20"></a>  <span class="dt">legend.title =</span> <span class="st">&quot;Sex&quot;</span>, </span>
<span id="cb778-21"><a href="survival-curve-estimation.html#cb778-21"></a>  <span class="dt">conf.int =</span> <span class="ot">TRUE</span>, </span>
<span id="cb778-22"><a href="survival-curve-estimation.html#cb778-22"></a>  <span class="dt">ggtheme =</span> <span class="kw">theme_minimal</span>())</span></code></pre></div>
<p><img src="data-sci_files/figure-html/unnamed-chunk-360-1.png" width="672" /></p>

</div>
</div>
<!-- </div> -->
            </section>

          </div>
        </div>
      </div>
<a href="basic-concepts.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="appendix.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="assets/gitbook-2.6.7/js/app.min.js"></script>
<script src="assets/gitbook-2.6.7/js/lunr.js"></script>
<script src="assets/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="assets/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["data-sci.pdf", "data-sci.epub"],
"toc": {
"collapse": "subsection"
},
"toolbar": {
"position": "static"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
